"""The Python that runs inside Pyodide.

Lives under `web/src/` because it ships to the browser like everything else here, and is plain
CPython so `tests/test_solve_py.py` can test it without a runtime. Its imports below --
`geopandas`, `pyproj`, `shapely`, `typing`, and `reblock.contracts`/`reblock.permeability`
themselves -- are exactly what `reblock.permeability` already pulls in transitively (via
`reblock.contracts`, which it imports `Block` from, and which itself uses `typing`). Nothing here
adds a package to the browser's install.

`web/test/pyodide-parity.test.ts` runs this same file under the Pyodide runtime and checks its
answers against the ones CPython baked into `examples/authoring/block.json`. That is the only
thing that could catch an import added here, because this file has no Python test of its own
install cost -- an import whose package is missing from the distribution fails that test's boot
with a `ModuleNotFoundError` naming it (confirmed by fault injection, Task 5's report).

It calls `solve_egress`, NOT `permeability`: `permeability` runs two solves because it recomputes
the no-roads baseline every call, and that baseline is road-invariant (design §1.6) and already
baked into `examples/authoring/block.json` as `baseline.p0`. One solve per edit is what makes
re-solve-while-dragging affordable. MEASURED (Task 2 fault injection 2): the two agree bit for
bit on both reference roads, so this choice is about the COST of a second solve, not about the
two paths disagreeing numerically.

`AuthoringBundle` (and the columns it is built from) is the JSON shape of
`examples/authoring/block.json` -- `web/src/authoring.d.ts`'s `AuthoringBlock`, generated by
`scripts/gen_authoring_block.py`'s `DTS_TEMPLATE` (not by this file). It is defined here, not
there, because `block_from_bundle` is the reconstruction that reads it and `web/src/py/` cannot
be imported from `scripts/` (it ships to a browser); the baker imports it back the same way it
imports `block_from_bundle`, so there is one definition rather than two that could drift apart.
"""
from __future__ import annotations

from typing import TypedDict

import geopandas as gpd
from pyproj import CRS
from shapely.geometry import LineString, Point, Polygon

from reblock.contracts import Block
from reblock.permeability import WIDTH_COL, PermeabilityParams, solve_egress


class ReferenceCase(TypedDict):
    """One fixed road and `solve_egress`' own `1 - p/p0` for it -- `web/src/authoring.d.ts`'s
    `AuthoringReference`."""
    name: str
    road: list[list[float]]
    permeability: float


class NodesDict(TypedDict):
    """Per-parcel node columns, in parcel order -- `web/src/authoring.d.ts`'s `nodes`."""
    cx: list[float]
    cy: list[float]
    ground: list[bool]


class EdgesDict(TypedDict):
    """Per-edge columns, in `Mesh` order -- `web/src/authoring.d.ts`'s `edges`."""
    rows: list[int]
    cols: list[int]
    footpath_g: list[float]


class BaselineDict(TypedDict):
    """`solve_egress(block, None, params)`'s own answer -- `web/src/authoring.d.ts`'s `baseline`."""
    p0: float
    potential: list[float]


class AuthoringBundle(TypedDict):
    """The whole artifact's shape -- `web/src/authoring.d.ts`'s `AuthoringBlock`.
    `block_from_bundle` below reads a subset of these fields (everything except `nodes`, `edges`,
    `baseline` and `reference`, which are road-invariant/reference columns the baker bakes and
    checks, not inputs the reconstruction needs); the type carries all of them because it is the
    type of the JSON object callers actually hold, not a narrowed view of what one function reads
    from it."""
    block_id: str
    crs_epsg: int
    boundary: list[list[list[float]]]
    parcel_id: list[str]
    parcels: list[list[list[list[float]]]]
    streets: list[list[list[float]]]
    building_points: list[list[float]]
    nodes: NodesDict
    edges: EdgesDict
    baseline: BaselineDict
    reference: list[ReferenceCase]


class PyResult(TypedDict):
    """`solve`'s return -- mirrors the TypeScript `PyResult` interface (design §3) field for
    field, so the two read alike across the runtime boundary."""
    permeability: float
    roadMetres: float
    potential: list[float]
    conductance: list[float]


def block_from_bundle(bundle: AuthoringBundle) -> Block:
    """Rebuild a `Block` from an `examples/authoring/block.json`-shaped bundle.

    Extracted from `scripts/gen_authoring_block.py`'s own reconstruction, which now loads this
    function back (by path -- see that script's loader) so the baker and this runtime share one
    reconstruction instead of two that could drift apart.
    """
    crs = CRS.from_epsg(bundle["crs_epsg"])
    boundary_rings = bundle["boundary"]
    parcels = gpd.GeoDataFrame(
        {"parcel_id": bundle["parcel_id"],
         "geometry": [Polygon(rings[0], rings[1:]) for rings in bundle["parcels"]]},
        geometry="geometry", crs=crs)
    streets = gpd.GeoDataFrame(
        {"geometry": [LineString(coords) for coords in bundle["streets"]]},
        geometry="geometry", crs=crs)
    points = gpd.GeoDataFrame(
        {"geometry": [Point(x, y) for x, y in bundle["building_points"]]},
        geometry="geometry", crs=crs)
    return Block(block_id=bundle["block_id"], crs=crs,
                 boundary=Polygon(boundary_rings[0], boundary_rings[1:]),
                 parcels=parcels, streets=streets, building_points=points)


def adjacency_from_bundle(bundle: AuthoringBundle) -> list[set[int]]:
    """The parcel adjacency the bundle already carries, as `solve_egress` wants it.

    `edges.rows`/`edges.cols` ARE this adjacency: the baker computed them with
    `derive.adjacency.parcel_adjacency` and wrote them out precisely so the browser would not have
    to. Reconstructing the neighbour sets from them is exact, not an approximation -- MEASURED on
    `ZAF.9.3.1_1_5810`, `parcel_adjacency` returns 19,443 edges and the bundle carries 19,443.

    It was not being used. `block_from_bundle` rebuilds a `Block` from geometry alone and
    `solve()` called `solve_egress` without `adj`, so every solve recomputed the adjacency from
    scratch -- an STRtree query plus a shapely `snap().intersection()` per candidate pair. On the
    263-parcel block that was merely wasteful. On this one it is 418.9 ms of a 593.9 ms solve
    (68%), and under Pyodide it does not complete at all: it dies inside shapely's `intersection`
    with `NoGilError: Attempted to use PyProxy when Python GIL not held`, a fatal runtime error
    rather than a slow one.

    So this is the fix for a broken widget AND a 3x speedup on every block, the small one
    included -- 593.9 ms to 192.9 ms natively.
    """
    n = len(bundle["parcel_id"])
    adj: list[set[int]] = [set() for _ in range(n)]
    for i, j in zip(bundle["edges"]["rows"], bundle["edges"]["cols"], strict=True):
        adj[i].add(j)
        adj[j].add(i)
    return adj


def solve(block: Block, road: list[list[float]], p0: float,
          adj: list[set[int]] | None = None) -> PyResult:
    """One `solve_egress` call for a reader-drawn `road`, normalized against the caller-supplied
    `p0` (the bundle's baked no-roads baseline).

    `adj` is the bundle's own parcel adjacency, built once at boot by `adjacency_from_bundle` --
    see there for why passing it is the difference between a widget that works on a settlement
    block and one that kills the interpreter.

    Refused here if `road` has fewer than two points, ahead of the widget's own check: the
    widget's check exists so the reader never gets this far, this one is the contract a caller
    cannot skip. `PermeabilityParams()` is constructed with no arguments -- the wheel `micropip`
    installs ships `src/reblock` alone, so `conf/` cannot reach the browser, and the baked
    `examples/authoring/block.json` was itself baked against these same defaults.
    """
    if len(road) < 2:
        raise ValueError("a road needs at least two points")
    line = LineString([(x, y) for x, y in road])
    params = PermeabilityParams()
    roads = gpd.GeoDataFrame(
        {"geometry": [line], WIDTH_COL: [params.min_road_width_m]},
        geometry="geometry", crs=block.crs)
    sol = solve_egress(block, roads, params, adj=adj)
    return PyResult(
        permeability=1.0 - sol.p / p0,
        roadMetres=line.length,
        potential=sol.potential.tolist(),
        conductance=sol.conductance.tolist(),
    )
