"""Machine-generated MkDocs site page. PURE dir-reader in the spirit of
scripts/gen_example_readme.py: every number, table, and image on the generated page is read from
run artifacts already on disk (examples/*/meta.json, lens_*.csv, displacement_table.csv, frontier
CSVs, curve PNGs, before/after renders, and outputs/*/run.log kcomplexity lines). A section is
emitted only when its artifacts exist, so a partial checkout yields a partial (never-erroring,
never-stale) site. Prose is the only handwritten content: the per-method blurbs below, and the
docs/_intro.md partial that opens the page.

The whole site is ONE scrollable page: docs/index.md = _intro.md + a section per method + the
benchmarks section, each under its own heading so the sidebar TOC (Material's toc.integrate)
gives anchor navigation.

Usage:  python3 scripts/gen_site_pages.py
Emits:  docs/index.md, and copies the referenced images into docs/assets/ (MkDocs can only
        serve files under docs/).
"""
from __future__ import annotations

import ast
import csv
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
ASSETS = DOCS / "assets"
MC = ROOT / "examples" / "method-comparison"
MB = ROOT / "examples" / "multiblock_depth"
OUTPUTS = ROOT / "outputs"

GENERATED_NOTE = ("<!-- Generated by scripts/gen_site_pages.py from run artifacts on disk. "
                  "Do not edit by hand - the prose intro lives in docs/_intro.md; everything "
                  "else regenerates from the data. -->\n")


# ---------------------------------------------------------------- small helpers

def _num(x: float, nd: int = 0) -> str:
    return f"{x:,.{nd}f}"


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open() as f:
        return list(csv.DictReader(f))


def _copy_asset(src: Path, sub: str) -> str | None:
    """Copy src into docs/assets/<sub>/ and return its path relative to the docs root."""
    if not src.exists():
        return None
    name = src.name.replace(":", "-")           # keep the repo checkout-able on Windows
    dest = ASSETS / sub / name
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    return f"assets/{sub}/{name}"


def _img_row(items: list[tuple[str, str]]) -> str:
    head = "| " + " | ".join(lbl for lbl, _ in items) + " |"
    sep = "|" + "|".join(["---"] * len(items)) + "|"
    cells = " | ".join(f"![{lbl}]({url})" for lbl, url in items)
    return f"{head}\n{sep}\n| {cells} |\n"


# ---------------------------------------------------------------- data readers

def _frontier_terminal(rows: list[dict[str, str]], method: str) -> tuple[float, float] | None:
    """(terminal road_length_m, terminal benefit) for one method in a frontier CSV."""
    pts = [(float(r["road_length_m"]), float(r["benefit"])) for r in rows if r["method"] == method]
    return max(pts) if pts else None


def _mc_summary(method: str) -> dict[str, str] | None:
    """Terminal-point row for the single-block head-to-head, from the frontier + displacement CSVs."""
    ext = _frontier_terminal(_read_csv(MC / "frontier_external_connectivity.csv"), method)
    intr = _frontier_terminal(_read_csv(MC / "frontier_internal_connectivity.csv"), method)
    disp = next((r for r in _read_csv(MC / "displacement_table.csv") if r["method"] == method), None)
    if ext is None and disp is None:
        return None
    row: dict[str, str] = {}
    if ext is not None:
        row["road built"] = f"{_num(ext[0])} m"
        row["external connectivity"] = f"{ext[1]:.2f}"
    if intr is not None:
        row["internal connectivity"] = f"{intr[1]:.2f}"
    if disp is not None:
        row["homes displaced"] = _num(float(disp["terminal_displacement"]))
        row["% of homes"] = _pct(float(disp["pct_displaced"]))
    return row


def _mb_lens_rows(method: str) -> tuple[dict[str, str] | None, dict[str, str] | None]:
    """This method's row from lens A (fixed connectivity target) and lens B (matched budget)."""
    a = next((r for r in _read_csv(MB / "lens_a_external.csv") if r["method"] == method), None)
    b = next((r for r in _read_csv(MB / "lens_b_matched.csv") if r["method"] == method), None)
    return a, b


def _dict_table(row: dict[str, str]) -> str:
    head = "| " + " | ".join(row) + " |"
    sep = "|" + "|".join(["---"] * len(row)) + "|"
    return f"{head}\n{sep}\n| " + " | ".join(row.values()) + " |\n"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- outputs/ scanning (k-complexity)

def _run_method_target(run_dir: Path) -> str | None:
    cfg = run_dir / ".hydra" / "config.yaml"
    if not cfg.exists():
        return None
    m = re.search(r"_target_:\s*(reblock\.methods\.[\w.]+)", cfg.read_text())
    return m.group(1) if m else None


def _run_flag(run_dir: Path, key: str) -> str | None:
    cfg = run_dir / ".hydra" / "config.yaml"
    if not cfg.exists():
        return None
    m = re.search(rf"^\s+{key}:\s*(\S+)\s*$", cfg.read_text(), re.M)
    return m.group(1) if m else None


def _kcomplexity_lines(run_dir: Path) -> list[tuple[str, dict[str, float]]]:
    log = run_dir / "run.log"
    if not log.exists():
        return []
    out = []
    for line in log.read_text().splitlines():
        if "'kcomplexity'" not in line:
            continue
        m = re.search(r"INFO\] - (\S+) (\{.*\})\s*$", line)
        if m:
            out.append((m.group(1), ast.literal_eval(m.group(2))["kcomplexity"]))
    return out


def _k_runs(target_frag: str, flags: list[str]) -> tuple[list[str], list[list[str]], list[Path]]:
    """All committed-nothing single-block eval runs under outputs/ whose method matches.

    Returns (headers, rows, matching run dirs). Deduped on (block, metrics) so re-renders of the
    same run don't repeat.
    """
    headers = ["run", "block", "k before", "k after", "delta k", "added road (m)",
               "road components", *flags]
    rows: list[list[str]] = []
    dirs: list[Path] = []
    seen: set[tuple[str, float, float, float]] = set()
    if not OUTPUTS.exists():
        return headers, rows, dirs
    for d in sorted(p for p in OUTPUTS.iterdir() if p.is_dir()):
        target = _run_method_target(d)
        if target is None or target_frag not in target:
            continue
        lines = _kcomplexity_lines(d)
        if not lines:
            continue
        dirs.append(d)
        flag_vals = [_run_flag(d, f) or "—" for f in flags]
        for block, k in lines:
            key = (block, k["k_after"], k["added_road_length_m"], k["n_road_components"])
            if key in seen:
                continue
            seen.add(key)
            rows.append([f"`{d.name}`", f"`{block}`", _num(k["k_before"]), _num(k["k_after"]),
                         _num(k["delta_k"]), _num(k["added_road_length_m"]),
                         _num(k["n_road_components"]), *flag_vals])
    return headers, rows, dirs


def _k_render_pair(dirs: list[Path], sub: str) -> tuple[str, str] | None:
    """First before/after PNG render pair found among the matching run dirs."""
    for d in dirs:
        before = sorted(d.glob("*_before.png"))
        after = sorted(d.glob("*_after.png"))
        if before and after:
            b = _copy_asset(before[0], f"{sub}/{d.name}")
            a = _copy_asset(after[0], f"{sub}/{d.name}")
            if b and a:
                return b, a
    return None


# ---------------------------------------------------------------- method registry (prose only)

class M:
    def __init__(self, slug: str, title: str, blurb: str, *, mc_key: str | None = None,
                 mb_key: str | None = None, outputs_frag: str | None = None,
                 outputs_flags: list[str] | None = None, conf: str | None = None,
                 status: str | None = None) -> None:
        self.slug, self.title, self.blurb = slug, title, blurb
        self.mc_key, self.mb_key = mc_key, mb_key
        self.outputs_frag, self.outputs_flags = outputs_frag, outputs_flags or []
        self.conf, self.status = conf, status


METHODS = [
    M("peel", "Peel",
      "Route roads by steepest descent down the access-depth peel: every interior parcel links to "
      "a neighbour one BFS ring shallower, and each chain roots at the nearest street point. The "
      "union is a connected centreline network that reaches **every** parcel — full access by "
      "construction. It is the project's deterministic access-optimal baseline: it shows the "
      "ceiling on access improvement, and its cost (road length, fragmentation, zero regard for "
      "what is buildable) is the price of that ceiling.",
      outputs_frag="methods.peel", conf="peel"),
    M("clearance", "Clearance",
      "A greedy least-cost-path reblocker with one physical knob, `repulsion`. Each road is the "
      "least-cost path from the current deepest parcel to the existing road+street network on a "
      "grid whose edge costs repel from building points — the knob sweeps from aspirational "
      "straight roads to buildable roads that hug the maximum-clearance (Voronoi) gaps between "
      "homes. Roads are added until an access-depth target is met, so it spends the least road "
      "for the depth it buys.",
      mc_key="clearance", outputs_frag="methods.clearance", conf="clearance"),
    M("clearance_looped", "Clearance (looped)",
      "The `clearance` reblocker plus a bridge-tree loop-closure refiner: after the least-cost "
      "roads are placed, it greedily adds short connectors that remove bridges (single points of "
      "failure) from the network, up to a small budget share. The result keeps clearance's "
      "least-road efficiency while buying back the backup-route redundancy (internal "
      "connectivity) that pure trees lack.",
      mc_key="clearance_looped", mb_key="clearance_looped", conf="loop_closure"),
    M("greedy_arterial_buildable", "Greedy Arterial (buildable)",
      "Greedily insert the single straight arterial with the best objective gain per metre, one "
      "road at a time, with candidates snapped to the parcel-boundary graph so every road is "
      "buildable frontage. The evaluated configuration is `greedy_arterial_repulsion`: buildable "
      "mode with a soft, never-zero building-proximity (repulsion) cost, so benefit is scored "
      "per home displaced and roads thread the gaps *between* building clusters. It runs via "
      "CELF/lazy greedy, so it scales to settlement-size regions.",
      mc_key="greedy_arterial_repulsion", mb_key="greedy_arterial_repulsion",
      conf="greedy_arterial_repulsion"),
    M("osm_footpaths", "OSM Footpaths",
      "The reblocker whose \"proposed roads\" are the **real** informal circulation network — the "
      "worn footpaths people already walk, as mapped in OpenStreetMap (largely by Humanitarian "
      "OSM digitization) — clipped to the region, minus the parts that merely retrace existing "
      "streets. It is the as-built baseline every synthesized method is judged against: what do "
      "the actual paths score on the same lenses?",
      mc_key="osm_footpaths", mb_key="osm_footpaths", conf="osm_footpaths"),
    M("euclidean_grid", "Euclidean Grid",
      "Overlay a fixed, evenly-spaced orthogonal grid of candidate roads across the block — a "
      "Manhattan-style plan, as opposed to peel's parcel-by-parcel descent. With `seek_density` "
      "the grid is phase-shifted so a line runs through the densest parcel cluster, and with "
      "`adaptive` the densest cells get a finer infill layer (quadtree-like: coarse where sparse, "
      "fine where crowded). It trades some raw access for a single connected, legible, buildable "
      "network.",
      mc_key="euclidean_grid", mb_key="euclidean_grid", outputs_frag="methods.euclidean_grid",
      outputs_flags=["seek_density", "adaptive", "spacing"], conf="euclidean_grid"),
    M("dream_come_true", "Dream Come True", "", status="in progress"),
]

DREAM_BODY = """
!!! warning "In progress"
    `dream_come_true` does not have complete run artifacts yet, so this section carries no
    numbers. It will join the benchmark tables once a full evaluated run lands in `examples/`.

The idea: a reblocker whose proposed roads are the **desire lines people already walk** —
detected from the ground truth of use, not synthesized from geometry.

* **Phase 1 (shipped as [`osm_footpaths`](#osm-footpaths)):** pull the informal footpath
  network from OpenStreetMap, where Humanitarian OSM teams have already digitized worn paths
  from imagery. This delivered a working as-built baseline with no ML and full offline
  reproducibility (a committed per-region OSM snapshot).
* **Phase 2 (planned):** detect desire lines directly from satellite imagery, slotting into the
  same `DesireLineSource` seam Phase 1 defined. Deriving desire lines from cheap signals
  (imagery heuristics, building-point geometry) was probed and found not to match OSM's
  human-mapped network — see `docs/superpowers/notes/2026-07-15-desire-line-detection.md` in the
  repository — so this phase is where the real detector work lives.

Design and plan documents live in the repository under `docs/superpowers/specs/` and
`docs/superpowers/plans/` (`2026-07-15-dream-come-true-*`).
"""


# ---------------------------------------------------------------- section emitters

def _mc_section(m: M) -> list[str]:
    parts: list[str] = []
    before = _copy_asset(MC / "before.jpg", "method-comparison")
    after = _copy_asset(MC / f"after_{m.mc_key}.jpg", "method-comparison")
    summary = _mc_summary(m.mc_key or "")
    if not (before or after or summary):
        return parts
    parts.append("### Head-to-head on one deep block\n")
    parts.append("From the [method-comparison example](https://github.com/jmendoza167/"
                 "REU_Slum_Optimization/tree/main/examples/method-comparison): six reblockers on "
                 "`ZAF.9.3.1_1_40972`, the deepest topology-tractable block in the Cape Town "
                 "metro (263 parcels, up to 7 rings deep). Blue = added roads; building sites "
                 "shade grey to red by displacement risk; the depth heatmap goes pale as roads "
                 "reach every parcel.\n")
    if before and after:
        parts.append(_img_row([("before", before), (f"after `{m.mc_key}`", after)]))
    if summary:
        parts.append("\nAt this method's full build-out on that block (terminal point of its "
                     "benefit-vs-road frontier):\n")
        parts.append(_dict_table(summary))
    return parts


def _mb_section(m: M) -> list[str]:
    parts: list[str] = []
    matched = _copy_asset(MB / f"after_{m.mb_key}_matched.jpg", "multiblock_depth")
    ext70 = _copy_asset(MB / f"after_{m.mb_key}_ext70.jpg", "multiblock_depth")
    gif = _copy_asset(MB / f"reblock_{m.mb_key}.gif", "multiblock_depth")
    lens_a, lens_b = _mb_lens_rows(m.mb_key or "")
    if not (matched or ext70 or gif or lens_a or lens_b):
        return parts
    parts.append("### On the settlement-scale benchmark\n")
    parts.append("From the [Cape Town benchmark](#benchmarks) — the 12-block, 11,006-parcel "
                 "`multiblock_depth` region.\n")
    if gif:
        parts.append(f"Full road set added in drainage order, the deep interior draining as the "
                     f"network reaches in:\n\n![reblock animation]({gif})\n")
    imgs = [(lbl, u) for lbl, u in (("matched road budget", matched),
                                    ("external connectivity 0.70", ext70)) if u]
    if imgs:
        parts.append("Truncated to the same road budget as every other method (left) and to the "
                     "road needed to reach external connectivity 0.70 (right):\n")
        parts.append(_img_row(imgs))
    if lens_a:
        reached = lens_a["reached"] == "True"
        verdict = (f"reaches external connectivity {float(lens_a['reached_ext']):.2f} with "
                   f"**{_num(float(lens_a['road_length_m']))} m** of road, displacing "
                   f"{_num(float(lens_a['displacement']))} homes "
                   f"({_pct(float(lens_a['pct_displaced']))})"
                   if reached else
                   f"never reaches the 0.70 external-connectivity target — it plateaus at "
                   f"{float(lens_a['reached_ext']):.2f} after "
                   f"{_num(float(lens_a['road_length_m']))} m of road")
        parts.append(f"\n**Lens A (fixed outcome, target 0.70):** {verdict}.\n")
    if lens_b:
        parts.append(f"**Lens B (matched budget, {_num(float(lens_b['budget_m']))} m):** external "
                     f"connectivity {float(lens_b['external_connectivity']):.2f}, internal "
                     f"connectivity {float(lens_b['internal_connectivity']):.2f}, "
                     f"{_num(float(lens_b['displacement']))} homes displaced "
                     f"({_pct(float(lens_b['pct_displaced']))}).\n")
    return parts


def _k_section(m: M) -> list[str]:
    parts: list[str] = []
    if not m.outputs_frag:
        return parts
    headers, rows, dirs = _k_runs(m.outputs_frag, m.outputs_flags)
    if not rows:
        return parts
    parts.append("### Single-block k-complexity runs\n")
    parts.append("Access depth is peel-k: the number of BFS rings between the deepest parcel and "
                 "a street (`k after = 1` means every parcel fronts a road). `road components` "
                 "counts disconnected pieces in the proposed network — 1 is a single buildable "
                 "network. Read from the `outputs/*/run.log` evaluation logs on disk:\n")
    parts.append(_table(headers, rows))
    pair = _k_render_pair(dirs, "runs")
    if pair:
        parts.append("\n" + _img_row([("before", pair[0]), ("after", pair[1])]))
    return parts


def gen_method_section(m: M) -> str:
    parts = [f"## {m.title}\n"]
    if m.status:
        parts.append(f"**Status: {m.status}.**\n")
    if m.blurb:
        parts.append(m.blurb + "\n")
    if m.conf and (ROOT / "conf" / "method" / f"{m.conf}.yaml").exists():
        parts.append(f"Configuration: [`conf/method/{m.conf}.yaml`](https://github.com/"
                     f"jmendoza167/REU_Slum_Optimization/blob/main/conf/method/{m.conf}.yaml)\n")
    if m.slug == "dream_come_true":
        parts.append(DREAM_BODY)
    body = (_mc_section(m) if m.mc_key else []) + \
           (_mb_section(m) if m.mb_key else []) + _k_section(m)
    parts += body
    if m.slug == "peel" and not body:
        parts.append("*No evaluation artifacts for this method were found on disk.*\n")
    return "\n".join(parts)


def gen_benchmark_section() -> str:
    import json
    parts = ["## Benchmarks\n"]
    parts.append("Two committed, fully reproducible benchmarks: a single deep block where all six "
                 "methods (including the single-block-only `topology` optimizer) run head-to-head, "
                 "and a settlement-scale region where the scalable methods are graded on the "
                 "benefit-vs-added-road frontier.\n")

    # ---- part 1: single-block head-to-head -------------------------------------------------
    disp = _read_csv(MC / "displacement_table.csv")
    if disp:
        parts.append("### One deep block, six methods\n")
        parts.append("Block `ZAF.9.3.1_1_40972` — the deepest block (by the depth proxy "
                     "`sqrt(n*A)/P`) small enough for `topology` to run: 263 parcels, up to 7 "
                     "rings deep, auto-picked with no hand tuning.\n")
        before = _copy_asset(MC / "before.jpg", "method-comparison")
        if before:
            parts.append(f"![before]({before})\n")
        afters = [(p.name[len("after_"):-len(".jpg")], _copy_asset(p, "method-comparison"))
                  for p in sorted(MC.glob("after_*.jpg"))]
        afters = [(lbl, url) for lbl, url in afters if url]
        if afters:
            parts.append("After, per method:\n")
            for i in range(0, len(afters), 3):
                parts.append(_img_row(afters[i:i + 3]))
        ext_rows = _read_csv(MC / "frontier_external_connectivity.csv")
        int_rows = _read_csv(MC / "frontier_internal_connectivity.csv")
        methods = list(dict.fromkeys(r["method"] for r in disp))
        table_rows = []
        for meth in methods:
            ext = _frontier_terminal(ext_rows, meth)
            intr = _frontier_terminal(int_rows, meth)
            d = next(r for r in disp if r["method"] == meth)
            table_rows.append([f"`{meth}`",
                               f"{ext[1]:.2f}" if ext else "-",
                               f"{intr[1]:.2f}" if intr else "-",
                               _num(ext[0]) if ext else "-",
                               _num(float(d["terminal_displacement"])),
                               _pct(float(d["pct_displaced"]))])
        parts.append("\nTerminal (full build-out) point of each method's frontier:\n")
        parts.append(_table(["method", "external connectivity", "internal connectivity",
                             "road built (m)", "homes displaced", "% of homes"], table_rows))
        for curve in sorted(MC.glob("curve_*.png")) + sorted(MC.glob("displacement_*.png")):
            url = _copy_asset(curve, "method-comparison")
            if url:
                parts.append(f"![{curve.stem}]({url})\n")

    # ---- part 2: settlement scale -----------------------------------------------------------
    meta_path = MB / "meta.json"
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}
    if meta:
        parts.append("### Settlement scale: the `multiblock_depth` region\n")
        parts.append(f"The `depth` metric screened **{_num(meta['flagged'])} of "
                     f"{_num(meta['total_blocks'])}** Cape Town blocks and grew the top-scoring "
                     f"block (`{meta['deepest_block']}`, peel depth "
                     f"{meta['deepest_depth']:.0f}) into a **{meta['region_members']}-block "
                     f"region of {_num(meta['region_parcels'])} parcels** — mean depth "
                     f"{meta['region_mean_depth']:.1f} rings, mean density "
                     f"{meta['region_mean_density_per_ha']:.0f} buildings/ha.\n")
        if meta.get("maps_url"):
            parts.append(f"[See the region on Google Maps]({meta['maps_url']})\n")
        for name in ("screen.jpg", "region.jpg"):
            url = _copy_asset(MB / name, "multiblock_depth")
            if url:
                parts.append(f"![{name}]({url})\n")
        parts.append("#### The benefit-vs-road frontier\n")
        parts.append("Each method's benefit as cumulative added road grows — external "
                     "connectivity (access burden removed), internal connectivity (backup-route "
                     "redundancy), and displacement (a rising cost):\n")
        for pat in ("depth_vs_road_*.png", "curve_external_connectivity_*.png",
                    "curve_internal_connectivity_*.png", "displacement_*.png"):
            for p in sorted(MB.glob(pat)):
                url = _copy_asset(p, "multiblock_depth")
                if url:
                    parts.append(f"![{p.stem}]({url})\n")
        lens_a = _read_csv(MB / "lens_a_external.csv")
        if lens_a:
            parts.append("#### Lens A — road needed to reach external connectivity 0.70\n")
            parts.append(_table(
                ["method", "reached", "external connectivity", "road (m)", "homes displaced",
                 "% of homes"],
                [[f"`{r['method']}`", "yes" if r["reached"] == "True" else "**no**",
                  f"{float(r['reached_ext']):.2f}", _num(float(r["road_length_m"])),
                  _num(float(r["displacement"])), _pct(float(r["pct_displaced"]))]
                 for r in lens_a]))
        lens_b = _read_csv(MB / "lens_b_matched.csv")
        if lens_b:
            budget = _num(float(lens_b[0]["budget_m"]))
            parts.append(f"#### Lens B — every method at the same {budget} m road budget\n")
            parts.append(_table(
                ["method", "external connectivity", "internal connectivity", "homes displaced",
                 "% of homes"],
                [[f"`{r['method']}`", f"{float(r['external_connectivity']):.2f}",
                  f"{float(r['internal_connectivity']):.2f}", _num(float(r["displacement"])),
                  _pct(float(r["pct_displaced"]))] for r in lens_b]))
        matched = sorted(MB.glob("after_*_matched.jpg"))
        ext70 = sorted(MB.glob("after_*_ext*.jpg"))
        if matched or ext70:
            parts.append("#### Each method on the ground\n")
            parts.append("Same region, same access-depth colour scale (blue = at a street, red = "
                         "deep), displaced buildings marked.\n")
        for title, files in (("Matched road budget", matched),
                             ("Matched external-connectivity target (0.70)", ext70)):
            items = []
            for p in files:
                url = _copy_asset(p, "multiblock_depth")
                if url:
                    items.append((p.name[len("after_"):-len(".jpg")].rpartition("_")[0], url))
            if items:
                parts.append(f"**{title}:**\n")
                for i in range(0, len(items), 2):
                    parts.append(_img_row(items[i:i + 2]))
        cmd = meta.get("command")
        if cmd:
            parts.append("#### Reproduce\n")
            parts.append("The whole benchmark — data, maps, curves, tables — regenerates from one "
                         f"self-logging command:\n\n```bash\n{cmd}\n```\n")
    return "\n".join(parts)


def main() -> None:
    # leftovers from the earlier multi-page layout (both generated, both gitignored)
    if (DOCS / "methods").exists():
        shutil.rmtree(DOCS / "methods")
    (DOCS / "benchmark.md").unlink(missing_ok=True)

    intro_path = DOCS / "_intro.md"
    intro = intro_path.read_text() if intro_path.exists() else "# reblock\n"
    parts = [GENERATED_NOTE, intro.rstrip() + "\n"]
    parts += [gen_method_section(m) for m in METHODS]
    parts.append(gen_benchmark_section())
    page = DOCS / "index.md"
    page.write_text("\n".join(parts) + "\n")
    print(f"wrote {page.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
