"""Machine-generated MkDocs site page. PURE dir-reader in the spirit of
scripts/gen_example_readme.py: every number, table, and image on the generated page is read from
run artifacts already on disk (examples/*/meta.json, lens_*.csv, frontier_permeability.csv, curve
PNGs, before/after renders, and outputs/*/run.log kcomplexity lines). A section is
emitted only when its artifacts exist, so a partial checkout yields a partial (never-erroring,
never-stale) site. Prose is the only handwritten content: the per-method blurbs below, and the
docs/_partials/intro.md partial that opens the page.

The site is multi-page. This script writes only the GENERATED (gitignored) pages: docs/index.md
(Home -- docs/_partials/intro.md folded in, plus a hero figure), docs/methodology/index.md,
docs/methodology/screening.md, docs/methodology/permeability.md, and
docs/methodology/displacement.md (each from its own docs/_partials/*.md partial),
docs/methodology/methods/index.md (methods overview) and docs/methodology/methods/<slug>.md (one
page per method), docs/results/frontier.md, docs/results/bakeoff.md and docs/results/nairobi.md
(Results), and docs/reproduce.md (the exact command behind every flagship, read from each
examples/*/meta.json). The handwritten prose pages -- docs/background.md, docs/team.md -- are
committed and this script never creates, reads, or overwrites them; docs/_partials/*.md are the
committed partials it reads (excluded from the built site) and folds into the generated pages.

Usage:  python3 scripts/gen_site_pages.py
Emits:  docs/index.md, docs/methodology/*.md, docs/methodology/methods/*.md, docs/results/*.md,
        docs/reproduce.md, and copies referenced images into docs/assets/ (MkDocs can only serve
        files under docs/).
"""
from __future__ import annotations

import ast
import csv
import importlib.util
import json
import re
import shutil
import struct
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
ASSETS = DOCS / "assets"
BRAND = DOCS / "brand"      # committed institutional marks, unlike the gitignored assets/
EXAMPLES = ROOT / "examples"
MC = ROOT / "examples" / "method-comparison"
MB = ROOT / "examples" / "multiblock_depth"
OUTPUTS = ROOT / "outputs"
BAKEOFF = ROOT / "examples" / "screen-bakeoff"
NAIROBI = ROOT / "examples" / "nairobi"
PERMGRAPH = ROOT / "examples" / "perm-graph"


def _load_friendly_method_name() -> Callable[[str], str]:
    """Load the stdlib-only display-name map straight from its file, WITHOUT importing the reblock
    package: CI runs this script with only mkdocs-material installed (reblock is not importable),
    and method_labels.py has no third-party or intra-package imports, so executing it directly is
    safe and keeps this script's stdlib-only contract. This is the single source of method display
    names (Option A) -- shared with the frontier-plot legend and the generated example READMEs."""
    path = ROOT / "src" / "reblock" / "method_labels.py"
    spec = importlib.util.spec_from_file_location("reblock_method_labels", path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    name: Callable[[str], str] = mod.friendly_method_name
    return name


friendly_method_name = _load_friendly_method_name()

GENERATED_NOTE = ("<!-- Generated by scripts/gen_site_pages.py from run artifacts on disk. "
                  "Do not edit by hand - the prose intro lives in docs/_partials/intro.md; "
                  "everything else regenerates from the data. -->\n")

# Whether the Home hero repeats the institutional mark below the header.
#
# True, because Material hides the header logo below 76.234375em -- on a phone, which is how most
# people arriving from the printed QR code will see this site, the header mark is simply not
# rendered. Dropping the hero lockup would leave those visitors no mark at all. On a wide screen
# the two do coexist, but at very different scale and role (a ~21px plate in the chrome versus a
# ~64px lockup in the masthead), so it reads as hierarchy rather than repetition.
#
# Set to False for one mark per page, header only. Nothing else needs changing -- the markup and
# its white card stay in place and stay gated on the asset actually existing.
HERO_LOCKUP = True


# ---------------------------------------------------------------- small helpers

def _num(x: float, nd: int = 0) -> str:
    return f"{x:,.{nd}f}"


def _pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def _read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _copy_asset(src: Path, sub: str) -> str | None:
    """Copy src into docs/assets/<sub>/ and return its path relative to the docs root."""
    if not src.exists():
        return None
    name = src.name.replace(":", "-")           # keep the repo checkout-able on Windows
    dest = ASSETS / sub / name
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dest)
    return f"assets/{sub}/{name}"


def _img_row(items: list[tuple[str, str]]) -> str:
    head = "| " + " | ".join(lbl for lbl, _ in items) + " |"
    sep = "|" + "|".join(["---"] * len(items)) + "|"
    cells = " | ".join(f"![{lbl}]({url})" for lbl, url in items)
    return f"{head}\n{sep}\n| {cells} |\n"


def _figure(url: str, alt: str, caption: str, *, fig_class: str = "",
            skip_lightbox: bool = False, attrs: str = "") -> str:
    """One captioned figure, emitted as a raw HTML block (no `markdown` attribute) so
    python-markdown passes it through untouched -- <figcaption> has no Markdown spelling, and
    mixing md_in_html parsing modes inside a <figure> is fragile. Any links in `caption` must
    therefore be written as HTML, and directory-relative (use_directory_urls is on).

    `skip_lightbox` marks an image as decoration rather than data; glightbox is configured with
    skip_classes: [skip-lightbox] so those images are not zoom targets.

    `attrs` is raw HTML attributes appended to the <figure> tag itself -- e.g. a widget's
    `data-widget`/`data-bundle`/... mount-point attributes (fix wave, I4). Those MUST
    land on the figure element and not on a wrapping <div>: `.sbu-figure-grid > figure` in
    docs/stylesheets/sbu.css resets `margin` and the mandatory `min-width: 0` on DIRECT children
    only, and a wrapping div would put the figure one level too deep to be reset."""
    img_cls = ' class="skip-lightbox"' if skip_lightbox else ""
    fig_attr = f' class="{fig_class}"' if fig_class else ""
    extra_attr = f" {attrs}" if attrs else ""
    return (f"<figure{fig_attr}{extra_attr}>\n"
            f'  <img src="{url}" alt="{alt}"{img_cls}>\n'
            f"  <figcaption>{caption}</figcaption>\n"
            f"</figure>\n")


# Wording is lifted from the prose already committed alongside these plots (see
# gen_benchmark_section), so a caption never asserts anything the page does not already say.
CURVE_CAPTIONS = {
    "curve_external_connectivity": "External connectivity as cumulative road grows, per method.",
    "curve_internal_connectivity": "Internal connectivity — the backup-route redundancy a pure "
                                   "tree lacks — as cumulative road grows, per method.",
    "depth_vs_road": "Access depth as cumulative road grows, per method.",
    "displacement": "Displacement — the share of homes a road set grazes — as cumulative road "
                    "grows, per method.",
}


def _curve_caption(stem: str) -> str:
    """Caption for a generated plot, keyed on its filename prefix. The block or region id is the
    remainder of the stem, so an unmapped plot still gets an honest, if plain, caption."""
    for prefix, text in CURVE_CAPTIONS.items():
        if stem.startswith(prefix):
            ident = stem[len(prefix):].strip("_")
            return f"{text} Region <code>{ident}</code>." if ident else text
    return f"<code>{stem}</code>"


# ---------------------------------------------------------------- data readers

def _frontier_terminal(rows: list[dict[str, str]], method: str) -> tuple[float, float] | None:
    """(terminal displacement, terminal permeability) for one method in a permeability frontier
    CSV -- the full-build-out point, i.e. the sampled prefix with the most road (== most
    displacement, since both axes are fractions in [0, 1) that only grow as road is added)."""
    pts = [(float(r["displacement"]), float(r["permeability"])) for r in rows
           if r["method"] == method]
    return max(pts) if pts else None


def _mc_summary(method: str) -> dict[str, str] | None:
    """Terminal-point (full build-out) summary for the single-block head-to-head, from the
    permeability frontier CSV: the displacement spent and the permeability reached at full build."""
    term = _frontier_terminal(_read_csv(MC / "frontier_permeability.csv"), method)
    if term is None:
        return None
    disp, perm = term
    return {"homes displaced": _pct(disp), "permeability": _pct(perm)}


def _mb_lens_rows(method: str) -> tuple[dict[str, str] | None, dict[str, str] | None]:
    """This method's row from the two permeability lenses: matched-displacement (equal home-cost,
    compare the permeability each buys) and matched-permeability (equal outcome, compare the homes
    each spends)."""
    disp = next((r for r in _read_csv(MB / "lens_displacement.csv") if r["method"] == method), None)
    perm = next((r for r in _read_csv(MB / "lens_permeability.csv") if r["method"] == method), None)
    return disp, perm


def _dict_table(row: dict[str, str]) -> str:
    head = "| " + " | ".join(row) + " |"
    sep = "|" + "|".join(["---"] * len(row)) + "|"
    return f"{head}\n{sep}\n| " + " | ".join(row.values()) + " |\n"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(out) + "\n"


def _screen_table() -> str:
    """The screen bake-off ranking, read straight from screen_comparison.csv's own columns --
    including `floor`, which already carries each metric's shipped absolute gate (empty for the
    two metrics never shipped as a gate). Deliberately NOT re-derived from conf/metric/*.yaml: a
    metric's CSV label (e.g. "depth_density proxy   √(nA)/P · n/A") does not round-trip to its
    config stem by splitting on whitespace -- `.split()[0]` lands on `depth_density`, which names
    a DIFFERENT, percentile-gated metric than `depth_density_proxy`. The CSV's own floor column
    has no such ambiguity. Empty string when the artifact is absent, per the dir-reader contract:
    a section is emitted only when its data exists."""
    rows = _read_csv(BAKEOFF / "screen_comparison.csv")
    if not rows:
        return ""
    body = [["metric", "AUC", "precision in top 1%", "shipped floor"]]
    for r in rows:
        body.append([r["metric"], _num(float(r["auc"]), 3), _pct(float(r["prec@1%"])),
                     r["floor"] or "—"])
    return _table(body[0], body[1:])


def _bakeoff_floors_table() -> str:
    """Both shipped screens at their absolute floors: pool size, precision, recall. Empty when
    the artifact is absent, per the dir-reader contract."""
    rows = [r for r in _read_csv(BAKEOFF / "screen_comparison.csv") if r.get("floor")]
    if not rows:
        return ""
    body = [[r["metric"], _num(float(r["floor_n"])), _pct(float(r["floor_prec"])),
             _pct(float(r["floor_recall"]))] for r in rows]
    return _table(["screen at its floor", "blocks", "precision", "recall"], body)


def _bakeoff_figures() -> str:
    """The three committed bake-off figures, in narrative order. Each is emitted only if present,
    per the dir-reader contract."""
    wanted = [("precision_recall.png", "Precision and recall across the candidate screens."),
              ("city_map.png", "Where the shipped screen and its predecessor disagree, city-wide."),
              ("settlements.png",
               "The settlements of sharpest disagreement, zoomed — gold traces each settlement's "
               "real extent; green marks blocks the new default gains, red marks blocks it "
               "drops.")]
    out: list[str] = []
    for name, caption in wanted:
        url = _copy_asset(BAKEOFF / name, "bakeoff")
        if url:
            out.append(_figure(url, caption, caption))
    return "\n\n".join(out)


def _perm_graph_figures() -> str:
    """The Permeability section's figure grid: the egress graph, conductance and current, before
    and after, laid out in `.sbu-figure-grid` (docs/stylesheets/sbu.css) -- two columns, not four
    stacked <figure>s. The whole reason a before/after pair shares one width norm and one node
    `vmax` is so the two can be *compared*; stacked four deep with a ~1.7 MB image between each,
    that comparison cannot be made. Figures are emitted row-major (conductance-before,
    conductance-after, current-before, current-after) so grid auto-flow lands layer-as-row x
    before/after-as-column (fix round 1, Finding F4 -- an earlier version of this docstring called
    the stacked output "the ... 2x2", a comment asserting something the code did not do).

    Every number is read from `examples/perm-graph/perm_graph.json`, written by
    `scripts/gen_perm_graph.py` beside the images. Typing one here would reintroduce the drift
    class the truth pass closed -- and `_intro.md`'s "seven methods" is the proof that a figure
    does not have to look like a metric to rot.

    The legend (blue = a road raised this edge, the pale-blue band = the road corridor itself,
    halo = grounded parcel) and the block-level facts (id, parcel/edge counts) are stated once, in
    a lead sentence above the grid -- repeating them per caption would just be Finding F5 again
    under cover of fixing F3. Each caption is trimmed to what is unique to its own panel: the
    layer, the state, and, for the "after" panels only, the road length and permeability reached.

    The width claim names GREY edges specifically, not "footpath-mesh": upgraded (road) edges are
    footpath-mesh edges too (the mesh has no other kind for a road to raise -- see this file's
    intro sentence, which counts them among the same `n_edges`), so scoping the claim to
    "footpath-mesh" does not exclude them, and an earlier fix that tried exactly that word left the
    claim still false of the 65 blue edges, which draw at a fixed width by design rather than one
    derived from their conductance or current (`render_graph`'s docstring, src/reblock/render.py).
    The caption now says so explicitly, with the upgraded-edge count read from `n_upgraded` in the
    artifact rather than typed as `65`. Node colour is stated once, as one scale shared across the
    panels -- not "the same scale as the heatmaps above": there are no heatmaps on this page, only
    these four images (fix round 1, Finding F1).

    The current/after figure -- and ONLY that one -- carries `data-widget="perm-graph"` mount-point
    attributes on its own `<figure>` (Task 6; moved onto the figure itself rather than a wrapping
    `<div>` in the fix wave, I4 -- see `_figure`'s docstring for why): a reader drags a slider along
    the road build-out order and watches current concentrate into each new road while permeability
    climbs, using the same bundle.json baked in Task 1. The other three panels stay plain
    `<figure>`s; the widget adds one interactive view, not four. `data-prefix` is read straight from
    `bundle.json`'s `lens_b_index` (fix wave, I8) so the mount point -- not the widget's boot code
    -- declares the state it must show before the reader touches the slider, right next to the
    caption that already claims it.
    """
    meta = json.loads((PERMGRAPH / "perm_graph.json").read_text(encoding="utf-8"))
    block, method = meta["block_id"], friendly_method_name(meta["method"])
    p_after, road_m = meta["permeability_after"] * 100.0, meta["road_m"]
    n_parcels, n_edges, n_upgraded = meta["n_parcels"], meta["n_edges"], meta["n_upgraded"]

    figs: list[str] = []
    for layer in ("conductance", "current"):
        for state, roads_clause in (
            ("before", "No new roads."),
            ("after", f"Under {method}'s roads at the matched-permeability standard: "
                      f"{road_m:,.0f} m of road, reaching {p_after:.1f}% permeability."),
        ):
            url = _copy_asset(PERMGRAPH / f"graph_{layer}_{state}.png", "perm-graph")
            if url is None:
                continue
            caption = (f"Grey edge width is {layer} on the footpath mesh; the {n_upgraded} "
                      f"road-raised edges (blue) draw at a fixed width instead. {roads_clause}")
            # Only THIS figure -- current, after -- gets the interactive mount point. It is the
            # one the fallback PNG (graph_current_after.png) and its caption above already
            # describe, so booting the widget here is fallback parity, not a fourth copy of the
            # same widget: wrapping all four figures would replace three distinct images with
            # three copies of the same slider. The mount attributes land on the <figure> ITSELF
            # (via `_figure`'s `attrs`), not a wrapping <div> -- see `_figure`'s docstring.
            attrs = ""
            if layer == "current" and state == "after":
                bundle_url = _copy_asset(PERMGRAPH / "bundle.json", "perm-graph")
                if bundle_url:
                    # lens_b_index read straight from the artifact, not retyped: the mount point
                    # declares the boot prefix here, beside the caption it has to match, rather
                    # than the widget hardcoding it on every boot (fix wave, I8).
                    bundle_meta = json.loads(
                        (PERMGRAPH / "bundle.json").read_text(encoding="utf-8"))
                    attrs = (f'data-widget="perm-graph" data-bundle="{bundle_url}" '
                            f'data-layer="current" '
                            f'data-prefix="{bundle_meta["lens_b_index"]}"')
            figs.append(_figure(url, f"egress graph, {layer}, {state} roads", caption, attrs=attrs))
    if not figs:
        return ""

    intro = (
        f"Block {block}: {n_parcels} parcels, {n_edges} footpath-mesh edges. Node colour is "
        f"egress potential φ, on one scale shared across these panels, dark meaning a harder "
        f"escape. Blue edges are the ones a road raised, and the pale-blue band is the road "
        f"corridor itself, drawn at its own width; haloed nodes front the existing street and "
        f"drain straight to ground."
    )
    return f'{intro}\n\n<div class="sbu-figure-grid">\n' + "".join(figs) + "</div>\n"


# ---------------------------------------------------------- the Frontier widget's mount point
#
# The widget's colours, labels, stroke widths, tick target and pad are NOT here: fix round 1 moved
# them into examples/method-comparison/frontier.json, where scripts/gen_frontier_bundle.py bakes
# them from reblock.emit -- the module that draws the fallback PNG the widget replaces -- so the two
# charts agree by construction rather than by this file and that one being kept in step by hand.
# What stays here is what belongs to the PAGE: the bundle's URL, the block id, the two boot targets
# beside the caption that states them, and the fallback image's own aspect ratio.
#
# Every attribute below is a SCALAR. The previous round passed two JSON payloads, which put literal
# `{`/`}` and `&quot;` into a markdown raw-HTML block. python-markdown stashes such a block before
# any inline or attr_list pass, so it was very probably fine -- and unlike the earlier claim in
# this comment, that IS checkable here: `/usr/bin/python3` carries python-markdown 3.5.2 and all
# five extensions mkdocs.yml configures are core. Rendering this page through that exact set keeps
# the <figure>, its six data-* attributes, the <img> and the <figcaption> intact (fix round 2).
# Scalars stay, because a payload that needs no escaping cannot be broken by an escaping change;
# what is gone is the pretence that the question was unanswerable. `mkdocs` itself -- theme, nav,
# --strict -- has since been run locally (mkdocs 1.6.1 + Material lives in a rattler cached env;
# see the backlog's piece-D entry for the path): exit 0, and the rendered <figure> keeps all six
# data-* attributes, its <img> and its <figcaption>. A BROWSER is still absent, so the chart's
# real glyph metrics, drag feel and legend wrapping remain unverified.


def _png_aspect(path: Path) -> float:
    """A PNG's width/height, from the IHDR fields in its first 24 bytes (stdlib `struct`, no
    Pillow). Read rather than restated as a constant so the widget's box is the same shape as the
    fallback image it replaces, and cannot drift from it when the plot's figsize changes."""
    with path.open("rb") as f:
        head = f.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"not a PNG: {path}")
    width, height = struct.unpack(">II", head[16:24])
    # int() on both: struct.unpack is typed as tuple[Any, ...], and an Any-valued division makes the
    # declared float return type unverifiable (mypy --strict's no-any-return).
    return int(width) / int(height)


def _frontier_figure() -> str:
    """The Methods index's one interactive figure: every method's permeability-against-displacement
    curve on the pinned single block, with the two calibrated standards as draggable targets.

    The fallback PNG stays IN the figure. mount.ts's error path tells the reader "the static image
    above still applies", which is only true while the image is there -- so the widget removes it
    itself, and only once it has actually drawn a chart in its place.

    Both target attributes come from `frontier.json` (`matched_displacement`,
    `matched_permeability`), never typed here: they are the same two cutoffs the fallback PNG draws
    as dashed guides and the caption below states, so the widget cannot boot contradicting either.
    Emits nothing when the artifacts are absent, like every other figure on this site.
    """
    path = MC / "frontier.json"
    if not path.exists():
        return ""
    bundle = json.loads(path.read_text(encoding="utf-8"))
    block = bundle["block_id"]
    png = MC / f"frontier_{block}.png"
    img_url = _copy_asset(png, "method-comparison")
    bundle_url = _copy_asset(path, "method-comparison")
    if img_url is None or bundle_url is None:
        return ""

    attrs = (f'data-widget="frontier" data-bundle="{bundle_url}" '
             f'data-target-displacement="{bundle["matched_displacement"]}" '
             f'data-target-permeability="{bundle["matched_permeability"]}" '
             f'data-aspect="{_png_aspect(png)}"')
    # The two standards are stated as WHOLE percentages, the same `{:.0%}` the fallback PNG's own
    # legend uses for its two dashed guides (emit.compare_report) and the same text the widget's
    # slider labels show -- not the site's usual one-decimal `_pct`, which would read 10.0% beside
    # an image that reads 10%.
    caption = (
        f"Permeability against displacement on block <code>{block}</code>, every method overlaid. "
        f"The two dashed guides are the calibrated standards every method here is graded against — "
        f"{bundle['matched_displacement']:.0%} displacement and "
        f"{bundle['matched_permeability']:.0%} permeability. Drag either guide, or use the "
        f"sliders, to ask which methods clear it and at what least road."
    )
    return _figure(img_url, f"permeability against displacement for every method on block {block}",
                   caption, attrs=attrs)


def _bakeoff_scale() -> str:
    """Survey scale, read from the ground-truth artifact rather than typed into prose -- and a
    COMPLETE SENTENCE, never a noun phrase (ruling F5). The generator's dir-reader contract lets
    ground_truth.json be absent on a partial checkout, in which case this returns "" -- a noun
    phrase spliced mid-sentence would then leave a dangling fragment ("The survey covers ."); a
    whole sentence simply disappears instead, and docs/_partials/bakeoff.md places it as its own
    paragraph so the section around it reads correctly either way."""
    path = BAKEOFF / "ground_truth.json"
    if not path.exists():
        return ""
    g = json.loads(path.read_text(encoding="utf-8"))
    return (f"That survey contains {_num(g['structures'])} dwelling polygons, which cluster into "
            f"{_num(g['settlements'])} settlements and mark {_num(g['informal_blocks'])} of "
            f"{_num(g['total_blocks'])} Cape Town blocks informal.")


def _nairobi_table() -> str:
    """One row per Nairobi variant, read from its own artifacts. Absent variants simply do not
    appear -- a partial checkout yields a shorter table, never a placeholder row (same dir-reader
    contract as _k_runs, guarded on NAIROBI.exists() for the same reason that one guards on
    OUTPUTS.exists() before iterating).

    Ruling F6: a field missing from one variant's meta.json renders as an em dash for THAT row,
    never a fabricated number. This mirrors the guarded `meta.get(...)` pattern _key_figures()
    already uses -- not the brief's original `_num(meta.get("region_members", 0))`, which would
    publish a confident 0 for a field that was simply never written."""
    rows: list[list[str]] = []
    if not NAIROBI.exists():
        return ""
    for d in sorted(p for p in NAIROBI.iterdir() if p.is_dir()):
        meta_path = d / "meta.json"
        if not meta_path.exists():
            continue
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        methods = {r["method"] for r in _read_csv(d / "lens_permeability.csv")}
        rows.append([f"[{d.name}](https://github.com/GeoffChurch/REU_Slum_Optimization/"
                     f"tree/main/examples/nairobi/{d.name})",
                     f"`{meta['metric']}`" if meta.get("metric") else "—",
                     _num(meta["region_members"]) if meta.get("region_members") else "—",
                     "yes" if "osm_footpaths" in methods else "—"])
    if not rows:
        return ""
    return _table(["variant", "metric", "blocks in region", "OSM baseline"], rows)


def _repro_commands() -> str:
    """Every flagship's regeneration command, read from its own meta.json. Never typed here: a
    command that drifts from the artifact it claims to produce is the same defect as a stale
    number."""
    rows: list[list[str]] = []
    for meta_path in sorted(EXAMPLES.glob("*/meta.json")) + sorted(
            EXAMPLES.glob("*/*/meta.json")):
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        cmd = meta.get("command")
        if not cmd:
            continue
        rows.append([meta_path.parent.relative_to(EXAMPLES).as_posix(), f"`{cmd}`"])
    if not rows:
        return ""
    return _table(["flagship", "command"], rows)


# ---------------------------------------------------------------- outputs/ scanning (k-complexity)

def _run_method_target(run_dir: Path) -> str | None:
    cfg = run_dir / ".hydra" / "config.yaml"
    if not cfg.exists():
        return None
    m = re.search(r"_target_:\s*(reblock\.methods\.[\w.]+)", cfg.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def _run_flag(run_dir: Path, key: str) -> str | None:
    cfg = run_dir / ".hydra" / "config.yaml"
    if not cfg.exists():
        return None
    m = re.search(rf"^\s+{key}:\s*(\S+)\s*$", cfg.read_text(encoding="utf-8"), re.M)
    return m.group(1) if m else None


def _kcomplexity_lines(run_dir: Path) -> list[tuple[str, dict[str, float]]]:
    log = run_dir / "run.log"
    if not log.exists():
        return []
    out = []
    for line in log.read_text(encoding="utf-8").splitlines():
        if "'kcomplexity'" not in line:
            continue
        m = re.search(r"INFO\] - (\S+) (\{.*\})\s*$", line)
        if m:
            out.append((m.group(1), ast.literal_eval(m.group(2))["kcomplexity"]))
    return out


def _k_runs(target_frag: str, flags: list[str]) -> tuple[list[str], list[list[str]], list[Path]]:
    """All committed-nothing single-block eval runs under outputs/ whose method matches.

    Returns (headers, rows, matching run dirs). Deduped on (block, metrics) so re-renders of the
    same run don't repeat.
    """
    headers = ["run", "block", "k before", "k after", "delta k", "added road (m)",
               "road components", *flags]
    rows: list[list[str]] = []
    dirs: list[Path] = []
    seen: set[tuple[str, float, float, float]] = set()
    if not OUTPUTS.exists():
        return headers, rows, dirs
    for d in sorted(p for p in OUTPUTS.iterdir() if p.is_dir()):
        target = _run_method_target(d)
        if target is None or target_frag not in target:
            continue
        lines = _kcomplexity_lines(d)
        if not lines:
            continue
        dirs.append(d)
        flag_vals = [_run_flag(d, f) or "—" for f in flags]
        for block, k in lines:
            key = (block, k["k_after"], k["added_road_length_m"], k["n_road_components"])
            if key in seen:
                continue
            seen.add(key)
            rows.append([f"`{d.name}`", f"`{block}`", _num(k["k_before"]), _num(k["k_after"]),
                         _num(k["delta_k"]), _num(k["added_road_length_m"]),
                         _num(k["n_road_components"]), *flag_vals])
    return headers, rows, dirs


def _k_render_pair(dirs: list[Path], sub: str) -> tuple[str, str] | None:
    """First before/after PNG render pair found among the matching run dirs."""
    for d in dirs:
        before = sorted(d.glob("*_before.png"))
        after = sorted(d.glob("*_after.png"))
        if before and after:
            b = _copy_asset(before[0], f"{sub}/{d.name}")
            a = _copy_asset(after[0], f"{sub}/{d.name}")
            if b and a:
                return b, a
    return None


# ---------------------------------------------------------------- method registry (prose only)

class M:
    def __init__(self, slug: str, title: str, blurb: str, *, idea: str = "",
                 badge: str = "evaluated", mc_key: str | None = None, mb_key: str | None = None,
                 outputs_frag: str | None = None, outputs_flags: list[str] | None = None,
                 conf: str | None = None, status: str | None = None,
                 published: bool = True) -> None:
        self.slug, self.title, self.blurb = slug, title, blurb
        self.idea, self.badge = idea, badge
        self.mc_key, self.mb_key = mc_key, mb_key
        self.outputs_frag, self.outputs_flags = outputs_frag, outputs_flags or []
        self.conf, self.status = conf, status
        # published=False keeps the method OUT of the Methods overview, so that page never links
        # to something the site does not build. It does NOT stop the page file being written --
        # exclude_docs in mkdocs.yml is the actual publish switch, and the file staying on disk
        # keeps its prose recoverable. THE TWO MUST BE KEPT IN SYNC: unpublishing a method means
        # published=False here AND its path in exclude_docs there.
        self.published = published

    @property
    def display_title(self) -> str:
        """Option-A display name: the friendly label for this method's key from method_labels.py,
        falling back to the hand-written title when the key is unmapped (peel/clearance/dream)."""
        key = self.mb_key or self.mc_key or self.slug
        name = friendly_method_name(key)
        return name if name != key else self.title


METHODS = [
    M("peel", "Peel",
      "Route roads by steepest descent down the access-depth peel: every interior parcel links to "
      "a neighbour one BFS ring shallower, and each chain roots at the nearest street point. The "
      "union is a connected centreline network that reaches **every** parcel — full access by "
      "construction. It is the project's deterministic access-optimal baseline: it shows the "
      "ceiling on access improvement, and its cost (road length, fragmentation, zero regard for "
      "what is buildable) is the price of that ceiling.",
      idea="steepest descent down the access-depth peel — the access-optimal baseline",
      badge="baseline", outputs_frag="methods.peel", conf="peel"),
    M("clearance", "Clearance",
      "A greedy least-cost-path reblocker with one physical knob, `repulsion`. Each road is the "
      "least-cost path from the current deepest parcel to the existing road+street network on a "
      "grid whose edge costs repel from building points — the knob sweeps from aspirational "
      "straight roads to buildable roads that hug the maximum-clearance (Voronoi) gaps between "
      "homes. Roads are added until an access-depth target is met, so it spends the least road "
      "for the depth it buys.",
      idea="least-cost paths that repel from homes",
      mc_key="clearance", outputs_frag="methods.clearance", conf="clearance"),
    M("clearance_looped", "Clearance (looped)",
      "The `clearance` reblocker plus a bridge-tree loop-closure refiner: after the least-cost "
      "roads are placed, it greedily adds short connectors that remove bridges (single points of "
      "failure) from the network, up to a small budget share. The result keeps clearance's "
      "least-road efficiency while buying back the backup-route redundancy (internal "
      "connectivity) that pure trees lack.",
      idea="clearance + loop-closing connectors for redundancy",
      mc_key="clearance_looped", mb_key="clearance_looped", conf="loop_closure"),
    M("greedy_arterial_buildable", "Greedy Arterial (buildable)",
      "Greedily insert the single straight arterial with the best objective gain per metre, one "
      "road at a time, with candidates snapped to the parcel-boundary graph so every road is "
      "buildable frontage. The evaluated configuration is `greedy_arterial_repulsion`: buildable "
      "mode with a soft, never-zero building-proximity (repulsion) cost, so benefit is scored "
      "per home displaced and roads thread the gaps *between* building clusters. It runs via "
      "CELF/lazy greedy, so it scales to settlement-size regions.",
      idea="best straight arterial per metre, snapped to buildable frontage",
      status=("not in the current benchmark lineup — it costs ~80x the wall-clock of every other "
              "method (37.6 s/block against 0.01-0.47 s) while trailing both lenses, so it was "
              "dropped from the examples; it remains a registered, tested method"),
      mc_key="greedy_arterial_repulsion", mb_key="greedy_arterial_repulsion",
      conf="greedy_arterial_repulsion"),
    M("cycle_native", "Loop Network",
      "Makes the **cycle** the primitive instead of the spur. Every other reblocker grows a tree "
      "and then, at best, bolts connectors onto it; this one's atomic move is a LOOP — a path out "
      "from the street to a chosen parcel, plus a second path back that avoids the first one's "
      "edges, so the union is a genuine circuit rather than a there-and-back. Candidates are "
      "scored by permeability gain per home displaced, the same currency the lenses use.\n\n"
      "The consequence is structural: it is **bridgeless by construction**, the only method here "
      "with essentially no single points of failure (bridge fraction ~0.03 against 0.51 for the "
      "looped tree and 1.00 for the grid and the LP). That property is real but currently "
      "invisible in the reported numbers, which price permeability and displacement only — so it "
      "reads as a strong second to the LP rather than as the different thing it is.",
      idea="the cycle, not the spur — bridgeless by construction",
      mc_key="cycle_native", mb_key="cycle_native", conf="cycle_native"),
    M("topology", "Topology",
      "The prior art: a whole-graph reblocker that solves the block in one shot rather than adding "
      "roads greedily. It is **single-block only** — a multi-block region gives it a disconnected "
      "source node and it fails — which is why it appears in the single-block flagship and nowhere "
      "else, and why that flagship exists at all.",
      idea="whole-graph, single-block — the prior art this project is measured against",
      mc_key="topology", conf="topology"),
    M("resistance_lp", "Direct Objective (LP)",
      "Chooses the **whole road set at once** with a linear program, rather than adding one road "
      "at a time, and budgets the currency the lenses actually score — **displacement** — instead "
      "of metres. The same metres cost wildly different numbers of homes depending on whether "
      "they run down a gap or through the dense interior, so budgeting metres optimises the wrong "
      "thing.\n\n"
      "Its decision variables are whole candidate *paths*, never free edges: choosing a path "
      "builds every segment of it, so any solution has already bought the route back to the "
      "street and connectivity is structural rather than repaired after rounding. Displacement is "
      "modelled as a maximum over segments rather than a sum, so two roads flanking the same "
      "building pay for it once — an exact discount a greedy cannot express, because marginal "
      "displacement is not CELF-safe.",
      idea="the whole road set solved at once by a linear program, budgeted in displacement",
      mb_key="resistance_lp", conf="resistance_lp"),
    M("greedy_arterial_access_displacement", "Frontage (street-priced)",
      "Drives straight arterials, like the other Greedy Arterial variants, but optimises a "
      "different thing: **the sum of squared access depths**. Depth is how many of other people's "
      "plots you cross to reach a public street — the quantity the block-complexity literature "
      "treats as the definition of the slum deficit — and squaring it means the deepest dwellings "
      "dominate, so the method drives roads at whoever is worst served.\n\n"
      "Two details earn their keep. It costs each candidate by **displacement** rather than by "
      "metres, which matters because displacement is the axis it is graded on: the same metres "
      "cost wildly different numbers of homes depending on where they run. And it is deliberately "
      "**not** run lazily — CELF's speedup needs a submodular objective, which holds for "
      "directness but not for access-burden reduction, where the lazy variant diverged from the "
      "exact greedy on every block tested and was slower on most of them.\n\n"
      "What it draws looks like a plan rather than an accretion: a handful of long chords "
      "threading between buildings and spanning the block, where a least-cost tree grows many "
      "short stubs.",
      idea="straight arterials chosen to cut the deepest access, priced in homes displaced",
      mb_key="greedy_arterial_access_displacement", conf="greedy_arterial"),
    M("osm_footpaths", "OSM Footpaths",
      "The reblocker whose \"proposed roads\" are the **real** informal circulation network — the "
      "worn footpaths people already walk, as mapped in OpenStreetMap (largely by Humanitarian "
      "OSM digitization) — clipped to the region, minus the parts that merely retrace existing "
      "streets. It is the as-built baseline every synthesized method is judged against: what do "
      "the actual paths score on the same lenses?",
      idea="the real as-built footpath network — the baseline to beat",
      mc_key="osm_footpaths", mb_key="osm_footpaths", conf="osm_footpaths"),
    M("euclidean_grid", "Euclidean Grid",
      "Overlay a fixed, evenly-spaced orthogonal grid of candidate roads across the block — a "
      "Manhattan-style plan, as opposed to peel's parcel-by-parcel descent. With `seek_density` "
      "the grid is phase-shifted so a line runs through the densest parcel cluster, and with "
      "`adaptive` the densest cells get a finer infill layer (quadtree-like: coarse where sparse, "
      "fine where crowded). It trades some raw access for a single connected, legible, buildable "
      "network.",
      idea="a density-adaptive Manhattan-style grid",
      mc_key="euclidean_grid", mb_key="euclidean_grid", outputs_frag="methods.euclidean_grid",
      outputs_flags=["seek_density", "adaptive", "spacing"], conf="euclidean_grid"),
    # Unpublished (see published= above and exclude_docs in mkdocs.yml): the method is still in
    # the pipeline and its page is still generated, it just is not built into the site while it
    # has no run artifacts. NOTE the Phase 1/Phase 2 write-up in DREAM_BODY below is the only
    # copy of that narrative anywhere in docs/ -- do not delete it when tidying.
    M("dream_come_true", "Dream Come True", "",
      idea="desire lines detected from imagery", status="in progress", published=False),
]

# The methods the Methods overview lists and links to. Anything unpublished is filtered out here
# so that page can never link to a file mkdocs.yml's exclude_docs drops from the build -- which
# MkDocs reports as "contains a link to ... which is excluded from the built site".
PUBLISHED_METHODS = [m for m in METHODS if m.published]


DREAM_BODY = """
!!! warning "In progress"
    `dream_come_true` does not have complete run artifacts yet, so this section carries no
    numbers. It will join the benchmark tables once a full evaluated run lands in `examples/`.

The idea: a reblocker whose proposed roads are the **desire lines people already walk** —
detected from the ground truth of use, not synthesized from geometry.

* **Phase 1 (shipped as [`osm_footpaths`](osm_footpaths.md)):** pull the informal footpath
  network from OpenStreetMap, where Humanitarian OSM teams have already digitized worn paths
  from imagery. This delivered a working as-built baseline with no ML and full offline
  reproducibility (a committed per-region OSM snapshot).
* **Phase 2 (planned):** detect desire lines directly from satellite imagery, slotting into the
  same `DesireLineSource` seam Phase 1 defined. Deriving desire lines from cheap signals
  (imagery heuristics, building-point geometry) was probed and found not to match OSM's
  human-mapped network — see `docs/superpowers/notes/2026-07-15-desire-line-detection.md` in the
  repository — so this phase is where the real detector work lives.

Design and plan documents live in the repository under `docs/superpowers/specs/` and
`docs/superpowers/plans/` (`2026-07-15-dream-come-true-*`).
"""


# ---------------------------------------------------------------- section emitters

def _mc_section(m: M) -> list[str]:
    parts: list[str] = []
    before = _copy_asset(MC / "before.png", "method-comparison")
    after = _copy_asset(MC / f"after_{m.mc_key}.png", "method-comparison")
    summary = _mc_summary(m.mc_key or "")
    if not (before or after or summary):
        return parts
    parts.append("## Head-to-head on one deep block\n")
    parts.append("From the [method-comparison example](https://github.com/GeoffChurch/"
                 "REU_Slum_Optimization/tree/main/examples/method-comparison): six reblockers on "
                 "`ZAF.9.3.1_1_40972`, the deepest topology-tractable block in the Cape Town "
                 "metro (263 parcels, up to 7 rings deep), graded on permeability (a flow measure "
                 "of how easily every parcel can reach a street) against displacement.\n")
    if before and after:
        parts.append("Blue = added roads; building sites shade grey to red by displacement risk; "
                     "the depth heatmap goes pale as roads reach every parcel.\n")
        parts.append(_img_row([("before", before), (f"after {m.display_title}", after)]))
    if summary:
        parts.append("\nAt this method's full build-out on that block (terminal point of its "
                     "permeability-vs-displacement frontier):\n")
        parts.append(_dict_table(summary))
    return parts


def _mb_section(m: M) -> list[str]:
    parts: list[str] = []
    matched = _copy_asset(MB / f"after_{m.mb_key}_matched.png", "multiblock_depth")
    ext70 = _copy_asset(MB / f"after_{m.mb_key}_ext70.png", "multiblock_depth")
    gif = _copy_asset(MB / f"reblock_{m.mb_key}.gif", "multiblock_depth")
    disp_row, perm_row = _mb_lens_rows(m.mb_key or "")
    if not (matched or ext70 or gif or disp_row or perm_row):
        return parts
    parts.append("## On the settlement-scale benchmark\n")
    parts.append("From the [Cape Town benchmark](../../results/frontier.md) — the 12-block, "
                 "11,006-parcel `multiblock_depth` region.\n")
    if gif:
        parts.append(f"Roads added busiest-first, each preceded by whatever it needs to reach the "
                     f"street, so every frame is a network you could actually build. The animation "
                     f"stops where the network first reaches the matched-permeability standard — "
                     f"every method's GIF ends at the same benefit, so what differs is the "
                     f"disruption spent getting there. The deep interior drains as the network "
                     f"reaches in:\n\n![reblock animation]({gif})\n")
    imgs = [(lbl, u) for lbl, u in (("matched road budget", matched),
                                    ("external connectivity 0.70", ext70)) if u]
    if imgs:
        parts.append("Truncated to the same road budget as every other method (left) and to the "
                     "road needed to reach external connectivity 0.70 (right):\n")
        parts.append(_img_row(imgs))
    if disp_row:
        note = ("" if disp_row["at_budget"] == "True"
                else " (it converges below the shared budget)")
        parts.append(f"\n**Matched displacement:** at **{_num(float(disp_row['road_m']))} m** of "
                     f"road it reaches permeability {_pct(float(disp_row['permeability']))}, "
                     f"displacing {_pct(float(disp_row['displacement']))} of homes{note}.\n")
    if perm_row:
        reached = perm_row["reached"] == "True"
        verdict = (f"reaches the permeability target with "
                   f"**{_num(float(perm_row['road_m']))} m** of road, displacing "
                   f"{_pct(float(perm_row['displacement']))} of homes"
                   if reached else
                   f"never reaches the permeability target — it plateaus at "
                   f"{_pct(float(perm_row['permeability']))} after "
                   f"{_num(float(perm_row['road_m']))} m of road")
        parts.append(f"**Matched permeability:** {verdict}.\n")
    return parts


def _k_section(m: M) -> list[str]:
    parts: list[str] = []
    if not m.outputs_frag:
        return parts
    headers, rows, dirs = _k_runs(m.outputs_frag, m.outputs_flags)
    if not rows:
        return parts
    parts.append("## Single-block k-complexity runs\n")
    parts.append("Access depth is peel-k: the number of BFS rings between the deepest parcel and "
                 "a street (`k after = 1` means every parcel fronts a road). `road components` "
                 "counts disconnected pieces in the proposed network — 1 is a single buildable "
                 "network. Read from the `outputs/*/run.log` evaluation logs on disk:\n")
    parts.append(_table(headers, rows))
    pair = _k_render_pair(dirs, "runs")
    if pair:
        parts.append("\n" + _img_row([("before", pair[0]), ("after", pair[1])]))
    return parts


def gen_method_section(m: M) -> str:
    parts = [f"# {m.display_title}\n"]
    if m.status:
        parts.append(f"**Status: {m.status}.**\n")
    if m.blurb:
        parts.append(m.blurb + "\n")
    if m.conf and (ROOT / "conf" / "method" / f"{m.conf}.yaml").exists():
        parts.append(f"Configuration: [`conf/method/{m.conf}.yaml`](https://github.com/"
                     f"GeoffChurch/REU_Slum_Optimization/blob/main/conf/method/{m.conf}.yaml)\n")
    if m.slug == "dream_come_true":
        parts.append(DREAM_BODY)
    body = (_mc_section(m) if m.mc_key else []) + \
           (_mb_section(m) if m.mb_key else []) + _k_section(m)
    parts += body
    if m.slug == "peel" and not body:
        parts.append("*No evaluation artifacts for this method were found on disk.*\n")
    return "\n".join(parts)


def gen_benchmark_section() -> str:
    parts = ["# Results\n"]
    parts.append("Two committed, fully reproducible benchmarks: a single deep block where all six "
                 "methods (including the single-block-only `topology` optimizer) run head-to-head, "
                 "and a settlement-scale region where the scalable methods are graded on the "
                 "permeability-vs-displacement frontier.\n")

    # ---- part 1: single-block head-to-head -------------------------------------------------
    mc_frontier = _read_csv(MC / "frontier_permeability.csv")
    if mc_frontier:
        parts.append("## One deep block, six methods\n")
        parts.append("Block `ZAF.9.3.1_1_40972` — the deepest block (by the depth proxy "
                     "`sqrt(n*A)/P`) small enough for `topology` to run: 263 parcels, up to 7 "
                     "rings deep, auto-picked with no hand tuning.\n")
        before = _copy_asset(MC / "before.png", "method-comparison")
        if before:
            parts.append(_figure(before, "Block ZAF.9.3.1_1_40972 before any roads are added",
                                 "The block before reblocking: 263 parcels, up to 7 rings deep."))
        afters_all = [(p.name[len("after_"):-len(".png")], _copy_asset(p, "method-comparison"))
                      for p in sorted(MC.glob("after_*.png"))]
        afters: list[tuple[str, str]] = [(lbl, url) for lbl, url in afters_all if url is not None]
        if afters:
            parts.append("After, per method:\n")
            for i in range(0, len(afters), 3):
                parts.append(_img_row(afters[i:i + 3]))
        methods = list(dict.fromkeys(r["method"] for r in mc_frontier))
        table_rows = []
        for meth in methods:
            term = _frontier_terminal(mc_frontier, meth)
            if term is None:
                continue
            d_disp, d_perm = term
            table_rows.append([friendly_method_name(meth), _pct(d_disp), _pct(d_perm)])
        parts.append("\nAt each method's full build-out (terminal point of its "
                     "permeability-vs-displacement frontier):\n")
        parts.append(_table(["method", "homes displaced", "permeability"], table_rows))
        for curve in sorted(MC.glob("curve_*.png")) + sorted(MC.glob("displacement_*.png")):
            url = _copy_asset(curve, "method-comparison")
            if url:
                parts.append(_figure(url, curve.stem, _curve_caption(curve.stem)))

    # ---- part 2: settlement scale -----------------------------------------------------------
    meta_path = MB / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    if meta:
        parts.append("## Settlement scale: the `multiblock_depth` region\n")
        parts.append(f"The `depth` metric screened **{_num(meta['flagged'])} of "
                     f"{_num(meta['total_blocks'])}** Cape Town blocks and grew the top-scoring "
                     f"block (`{meta['deepest_block']}`, peel depth "
                     f"{meta['deepest_depth']:.0f}) into a **{meta['region_members']}-block "
                     f"region of {_num(meta['region_parcels'])} parcels** — mean depth "
                     f"{meta['region_mean_depth']:.1f} rings, mean density "
                     f"{meta['region_mean_density_per_ha']:.0f} buildings/ha.\n")
        if meta.get("maps_url"):
            parts.append(f"[See the region on Google Maps]({meta['maps_url']})\n")
        scene_captions = {
            "screen.png": (f"The `depth` screen across the Cape Town metro: "
                           f"{_num(meta['flagged'])} of {_num(meta['total_blocks'])} blocks "
                           f"flagged."),
            "region.png": (f"The region grown from the top-scoring block: "
                           f"{meta['region_members']} blocks, "
                           f"{_num(meta['region_parcels'])} parcels."),
        }
        for name in ("screen.png", "region.png"):
            url = _copy_asset(MB / name, "multiblock_depth")
            if url:
                parts.append(_figure(url, name.removesuffix(".png"), scene_captions[name]))
        frontier_imgs: list[str] = []
        for pat in ("depth_vs_road_*.png", "curve_external_connectivity_*.png",
                    "curve_internal_connectivity_*.png", "displacement_*.png"):
            for p in sorted(MB.glob(pat)):
                url = _copy_asset(p, "multiblock_depth")
                if url:
                    frontier_imgs.append(_figure(url, p.stem, _curve_caption(p.stem)))
        if frontier_imgs:
            parts.append("### The permeability-vs-displacement frontier\n")
            parts.append("Each method's permeability (a flow measure of how easily every parcel "
                         "reaches a street) as cumulative road grows, against the displacement it "
                         "costs:\n")
            parts.extend(frontier_imgs)
        disp_lens = _read_csv(MB / "lens_displacement.csv")
        if disp_lens:
            parts.append("### Lens A — matched displacement: permeability bought at an equal "
                         "home-cost\n")
            parts.append(_table(
                ["method", "road (m)", "homes displaced", "permeability", "note"],
                [[friendly_method_name(r["method"]), _num(float(r["road_m"])),
                  _pct(float(r["displacement"])), _pct(float(r["permeability"])),
                  "" if r["at_budget"] == "True" else "converged below budget"]
                 for r in disp_lens]))
        perm_lens = _read_csv(MB / "lens_permeability.csv")
        if perm_lens:
            parts.append("### Lens B — matched permeability: homes displaced to reach the "
                         "standard\n")
            parts.append(_table(
                ["method", "road (m)", "homes displaced", "permeability", "note"],
                [[friendly_method_name(r["method"]), _num(float(r["road_m"])),
                  _pct(float(r["displacement"])), _pct(float(r["permeability"])),
                  "" if r["reached"] == "True" else "**target unreached**"]
                 for r in perm_lens]))
        matched = sorted(MB.glob("after_*_matched.png"))
        ext70 = sorted(MB.glob("after_*_ext*.png"))
        if matched or ext70:
            parts.append("### Each method on the ground\n")
            parts.append("Same region, same access-depth colour scale (blue = at a street, red = "
                         "deep), displaced buildings marked.\n")
        for title, files in (("Matched road budget", matched),
                             ("Matched external-connectivity target (0.70)", ext70)):
            items = []
            for p in files:
                url = _copy_asset(p, "multiblock_depth")
                if url:
                    key = p.name[len("after_"):-len(".png")].rpartition("_")[0]
                    items.append((friendly_method_name(key), url))
            if items:
                parts.append(f"**{title}:**\n")
                for i in range(0, len(items), 2):
                    parts.append(_img_row(items[i:i + 2]))
        cmd = meta.get("command")
        if cmd:
            parts.append("### Reproduce\n")
            parts.append("The whole benchmark — data, maps, curves, tables — regenerates from one "
                         f"self-logging command:\n\n```bash\n{cmd}\n```\n")
    return "\n".join(parts)


def gen_methods_overview() -> str:
    """The Methods section landing (docs/methodology/methods/index.md): PUBLISHED_METHODS as
    scannable cards, then the same set as a table. Both are emitted deliberately -- the cards
    are for choosing which method to read, the table is for comparing status and one-line ideas
    at a glance without scanning a grid. Prose (title, one-line idea, badge) is registry-driven;
    no run data."""
    parts = ["# The methods\n"]
    parts.append("Every method proposes a different road network for the same blocks; all are "
                 "graded on the same basis — permeability (the benefit) against displacement (the "
                 "cost). Each page shows the method's roads on the ground and its numbers from the "
                 "actual runs.\n")
    # That basis, as one figure, before the reader picks a method to read about: the interactive
    # frontier (falling back to its own static PNG). Placed here with no heading of its own on
    # purpose -- it illustrates the sentence directly above it, and a heading between that sentence
    # and the cards would leave the cards sitting under the wrong one.
    parts.append(_frontier_figure())

    cards = []
    for m in PUBLISHED_METHODS:
        label = m.status or m.badge
        cls = "pill-progress" if m.status else "pill-done"
        # Uppercase only the first letter -- str.capitalize() would lowercase the rest and turn
        # "Manhattan-style" into "manhattan-style", "OSM" into "osm".
        idea = m.idea[:1].upper() + m.idea[1:]
        cards.append(f"-   **[{m.display_title}]({m.slug}.md)**\n\n"
                     f"    {idea}.\n\n"
                     f'    <span class="pill {cls}">{label}</span>')
    parts.append('<div class="grid cards" markdown>\n\n' + "\n\n".join(cards) + "\n\n</div>\n")

    parts.append("## At a glance\n")
    rows = []
    for m in PUBLISHED_METHODS:
        label = m.status or m.badge
        cls = "pill-progress" if m.status else "pill-done"
        rows.append([f"[{m.display_title}]({m.slug}.md)", m.idea,
                     f'<span class="pill {cls}">{label}</span>'])
    parts.append(_table(["Method", "Idea", "Status"], rows))
    return "\n".join(parts)


def _hero_block() -> str:
    """Home hero figure: the grown settlement render, copied into assets/. Extension-agnostic (the
    example image pipeline is migrating JPG->PNG) and gated on existence, so a partial checkout
    yields no hero figure rather than a broken image. Marked skip-lightbox: it is the page's
    opening image, and the same render is zoomable on Results where it carries the argument."""
    for name in ("region.png", "region.jpg", "region.jpeg"):
        url = _copy_asset(MB / name, "home")
        if url:
            return _figure(
                url,
                "The grown Cape Town settlement region with proposed roads threaded through it",
                'A screened settlement grown into a multi-block region, with proposed roads '
                'threaded through it — see the full run on '
                '<a href="results/frontier/">Results</a>.',
                fig_class="sbu-hero__figure", skip_lightbox=True)
    return ""


def _hero_logo() -> str:
    """The official Stony Brook mark in the hero, emitted only when the asset is genuinely
    committed under docs/brand/. Same existence gate every artifact on this site gets: no asset,
    no markup. It is never substituted with a traced, redrawn, or approximated mark, and the
    surrounding CSS pads rather than scales it so clear space survives and the mark is never
    stretched or skewed."""
    if not HERO_LOCKUP:
        return ""
    # The VERTICAL lockup here, deliberately: the hero card is a masthead block with room for a
    # near-square mark, where the header's horizontal variant would look stranded.
    for name in ("sbu-logo.svg", "sbu-logo.png"):
        if (BRAND / name).exists():
            # Wrapped in its own white card: the mark is 2-colour (black wordmark, #990000
            # shield and "University") with no reversed variant, so it cannot sit on the red
            # hero directly. The card supplies the light ground and the clear space.
            return (f'<span class="sbu-hero__lockup">'
                    f'<img class="sbu-hero__logo skip-lightbox" src="brand/{name}"'
                    f' alt="Stony Brook University"></span>')
    return ""


def _key_result() -> str:
    """The headline finding, stated on the Home page in one sentence, entirely from Lens A of the
    settlement benchmark: the permeability the best method buys at the shared road budget, set
    against the as-built footpath network measured on the same basis. Emits nothing when the
    artifacts are absent, so a partial checkout drops the claim rather than inventing one."""
    rows = _read_csv(MB / "lens_displacement.csv")
    if not rows:
        return ""
    best = max(rows, key=lambda r: float(r["permeability"]))
    osm = next((r for r in rows if r["method"] == "osm_footpaths"), None)
    lead = (f"At a matched road budget, <strong>{friendly_method_name(best['method'])}</strong> "
            f"reaches <strong>{_pct(float(best['permeability']))} permeability</strong>")
    if osm is None:
        return f"{lead} across the 12-block benchmark region."
    return (f"{lead} — against <strong>{_pct(float(osm['permeability']))}</strong> for the "
            f"footpath network residents have already worn into the same settlement.")


def _key_figures() -> str:
    """The Home page's figures row: four measurements read straight from the benchmark artifacts.
    Each entry is dropped individually when its artifact is missing, and the whole row disappears
    if none survive -- no placeholder ever stands in for a number."""
    items: list[tuple[str, str]] = []

    meta_path = MB / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    if meta.get("region_parcels") and meta.get("region_members"):
        items.append((_num(meta["region_parcels"]),
                      f"parcels across the {meta['region_members']}-block benchmark region"))
    if meta.get("flagged") and meta.get("total_blocks"):
        items.append((_num(meta["flagged"]),
                      f"of {_num(meta['total_blocks'])} Cape Town blocks flagged by the depth "
                      f"screen"))

    disp = _read_csv(MB / "lens_displacement.csv")
    if disp:
        best = max(disp, key=lambda r: float(r["permeability"]))
        items.append((_pct(float(best["permeability"])),
                      f"permeability at a matched road budget "
                      f"({friendly_method_name(best['method'])})"))

    reached = [r for r in _read_csv(MB / "lens_permeability.csv") if r["reached"] == "True"]
    if reached:
        cheapest = min(reached, key=lambda r: float(r["displacement"]))
        items.append((_pct(float(cheapest["displacement"])),
                      f"of homes displaced to reach the shared permeability target "
                      f"({friendly_method_name(cheapest['method'])})"))

    if not items:
        return ""
    cells = "\n".join(f"  <div><dd>{value}</dd><dt>{label}</dt></div>" for value, label in items)
    return f'<dl class="sbu-keyfigures">\n{cells}\n</dl>'


_COUNT_WORDS = {1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six",
                7: "Seven", 8: "Eight", 9: "Nine", 10: "Ten", 11: "Eleven", 12: "Twelve"}


def _method_count() -> str:
    """The number of PUBLISHED methods, as an English word. Generated because typing it into prose
    is exactly how docs/_intro.md came to claim "Seven" while ten methods shipped."""
    n = sum(1 for m in METHODS if m.published)
    return _COUNT_WORDS.get(n, str(n))


# Marker name -> producer. A partial's <!-- NAME --> holes are filled from here; tests assert this
# mapping and the markers actually used in docs/_partials/ are the same set, in both directions.
MARKERS: dict[str, Callable[[], str]] = {
    "HEROLOGO": _hero_logo,
    "HERO": _hero_block,
    "KEYRESULT": _key_result,
    "KEYFIGURES": _key_figures,
    "METHODCOUNT": _method_count,
    "SCREENTABLE": _screen_table,
    "BAKEOFFSCALE": _bakeoff_scale,
    "BAKEOFFFLOORS": _bakeoff_floors_table,
    "BAKEOFFFIGS": _bakeoff_figures,
    "PERMGRAPHFIGS": _perm_graph_figures,
    "NAIROBITABLE": _nairobi_table,
    "REPROCOMMANDS": _repro_commands,
}

PARTIALS = DOCS / "_partials"


_LEADING_COMMENT = re.compile(r"\A\s*<!--.*?-->\s*", flags=re.S)


def _render_partial(name: str) -> str:
    """Read docs/_partials/<name>.md, strip its LEADING maintainer comment, and fill every known
    marker. Every partial opens with an internal note (do-not-edit pointer, marker inventory,
    sometimes ruling numbers or plan paths) that has no business in a public site's page source --
    HTML comments pass through python-markdown untouched into the built HTML. Only the leading
    comment is stripped: a partial may legitimately carry one later in its body (e.g.
    permeability.md's figure placeholder), and those must survive. Unknown markers are left alone
    so the closed-set test can catch them; a missing partial is an error, not an empty page."""
    text = (PARTIALS / f"{name}.md").read_text(encoding="utf-8")
    text = _LEADING_COMMENT.sub("", text, count=1).rstrip()
    for marker, produce in MARKERS.items():
        text = text.replace(f"<!-- {marker} -->", produce())
    return text


def _write_page(path: Path, body: str, *, depth: int, url_depth: int,
                title: str | None = None) -> None:
    """Write one generated page, fixing asset paths for BOTH link forms, which MkDocs treats
    differently:

    `depth` -- Markdown links `](assets/...)`. MkDocs resolves these against the SOURCE file, so a
    page nested `depth` levels below docs/ needs ../ per level; MkDocs then rewrites the output
    URL itself.

    `url_depth` -- raw HTML `src="assets/..."`, `href="assets/..."` and `data-bundle="assets/..."`
    (the widget mount point's fetch URL -- same rule, it is raw HTML too) inside the <figure>
    blocks. MkDocs does NOT touch raw HTML, so these must already be correct against the page's
    SERVED url. With use_directory_urls, results/frontier.md is served at
    <base>/results/frontier/ and methodology/methods/peel.md at
    <base>/methodology/methods/peel/, so the served depth is not the same as the source depth --
    results/frontier.md is depth 1 but url_depth 2. Getting this wrong 404s every figure -- or,
    for data-bundle, silently fails the widget's fetch -- on that page."""
    # YAML front matter, when given, sets the page's nav label. Without it MkDocs derives the
    # label from the FILENAME -- "clearance_looped" became "Clearance looped" in the sidebar, not
    # "Looped Tree" -- because it does not read the H1 for nav purposes. Emitting the title here
    # keeps method_labels.py the single source of the display name for the heading AND the nav,
    # instead of a hand-written copy in mkdocs.yml that silently goes stale.
    front = f'---\ntitle: "{title}"\n---\n' if title else ""
    text = front + GENERATED_NOTE + body.rstrip() + "\n"
    if depth:
        text = text.replace("](assets/", "](" + "../" * depth + "assets/")
    if url_depth:
        up = "../" * url_depth
        text = text.replace('src="assets/', f'src="{up}assets/')
        text = text.replace('href="assets/', f'href="{up}assets/')
        text = text.replace('data-bundle="assets/', f'data-bundle="{up}assets/')
    path.write_text(text, encoding="utf-8")


def _assert_widget_bundle_present(pages_with_widgets: bool) -> None:
    """A site built without `pixi run web` emits a <script> tag for a file that is not there: every
    widget silently fails to boot, the PNG fallbacks still render, and the page looks FINE. Turn
    that into a build failure. File existence needs no imports, so this respects the stdlib-only
    contract."""
    if pages_with_widgets and not (DOCS / "js" / "widgets.js").exists():
        raise SystemExit(
            "docs/js/widgets.js is missing but a page carries a widget mount point -- run "
            "`pixi run web` (CI does this in deploy-site.yml before mkdocs build)")


def main() -> None:
    # Generated (gitignored) pages only. The handwritten committed pages (background.md,
    # team.md) are never touched.
    (DOCS / "index.md").write_text(GENERATED_NOTE + _render_partial("intro") + "\n",
                                   encoding="utf-8")

    # reproduce.md serves at <base>/reproduce/ -- source depth 0, url_depth 1. Written directly
    # into docs/, not into a cleared subdirectory, so (unlike results/ and methodology/ below) it
    # is not subject to the rmtree/mkdir hazard those blocks document (ruling F4).
    _write_page(DOCS / "reproduce.md", _render_partial("reproduce"), depth=0, url_depth=1,
                title="Reproduce")

    results_dir = DOCS / "results"
    if results_dir.exists():
        shutil.rmtree(results_dir)
    results_dir.mkdir(parents=True, exist_ok=True)
    # results/frontier.md serves at <base>/results/frontier/ -- source depth 1, url_depth 2.
    _write_page(results_dir / "frontier.md", gen_benchmark_section(), depth=1, url_depth=2,
                title="Frontier benchmark")
    # results/bakeoff.md serves at <base>/results/bakeoff/ -- same depth/url_depth as frontier.md
    # above, and MUST follow the results_dir rmtree/mkdir block above it (ruling F4): an insertion
    # above that block would delete this page as soon as it was written.
    _write_page(results_dir / "bakeoff.md", _render_partial("bakeoff"), depth=1, url_depth=2,
                title="Screen bake-off")
    # results/nairobi.md serves at <base>/results/nairobi/ -- same depth/url_depth as its two
    # siblings above, and (ruling F4) MUST likewise follow the results_dir rmtree/mkdir block.
    _write_page(results_dir / "nairobi.md", _render_partial("nairobi"), depth=1, url_depth=2,
                title="Second city: Nairobi")

    # docs/methodology/ -- rebuilt from scratch each run. Every _write_page into this directory,
    # including the methodology/methods/ pages below, MUST come after this rmtree/mkdir, or it
    # deletes the page just written -- same reason permeability.md and displacement.md have to.
    methodology_dir = DOCS / "methodology"
    if methodology_dir.exists():
        shutil.rmtree(methodology_dir)
    methodology_dir.mkdir(parents=True, exist_ok=True)
    _write_page(methodology_dir / "index.md", _render_partial("methodology"),
                depth=1, url_depth=1, title="Methodology")
    _write_page(methodology_dir / "screening.md", _render_partial("screening"),
                depth=1, url_depth=2, title="Screening")
    _write_page(methodology_dir / "permeability.md", _render_partial("permeability"),
                depth=1, url_depth=2, title="Permeability")
    _write_page(methodology_dir / "displacement.md", _render_partial("displacement"),
                depth=1, url_depth=2, title="Displacement")

    methods_dir = methodology_dir / "methods"
    methods_dir.mkdir(parents=True, exist_ok=True)
    # methodology/methods/index.md serves at <base>/methodology/methods/ (2 segments);
    # methodology/methods/peel.md at <base>/methodology/methods/peel/ (3). Source depth is 2 for
    # both. Getting url_depth wrong 404s every figure on the page.
    _write_page(methods_dir / "index.md", gen_methods_overview(), depth=2, url_depth=2,
                title="The methods")
    for m in METHODS:
        _write_page(methods_dir / f"{m.slug}.md", gen_method_section(m), depth=2, url_depth=3,
                    title=m.display_title)

    # Scoped to exactly the GENERATED (gitignored) page set -- docs/index.md, docs/reproduce.md,
    # docs/methodology/**, docs/results/** -- never docs/superpowers/ or docs/_partials/. Both of
    # those are committed prose that can legitimately quote 'data-widget="perm-graph"' (this
    # file's own design spec does, as an example snippet) without a single generated page
    # actually carrying a mount point; scanning them would make the guard fire on a site that
    # built perfectly fine.
    generated_pages = ([DOCS / "index.md", DOCS / "reproduce.md"]
                       + sorted(methodology_dir.rglob("*.md"))
                       + sorted(results_dir.rglob("*.md")))
    pages_with_widgets = any('data-widget="' in p.read_text(encoding="utf-8")
                             for p in generated_pages if p.exists())
    _assert_widget_bundle_present(pages_with_widgets)

    print("wrote docs/index.md, docs/reproduce.md, docs/results/frontier.md, "
          "docs/methodology/*.md, docs/methodology/methods/*.md")


if __name__ == "__main__":
    main()
