"""Bake the per-method frontier table for the Methods index page's Frontier widget.

Every method's FULL drainage-ordered prefix table on the pinned block: road length, displacement and
permeability at m = 0..R. Both axes, because a target set on either one is answered against the
other -- and both are monotone in m, so the browser answers "which methods clear this target, and at
what least road" by the same binary search `budget.prefix_to_permeability` runs in Python, over the
same sequence. Not an interpolation.

784 prefixes across 8 methods, ~20 s of permeability solving. The parent design called full prefix
tables the long pole; at block scale they are not one. The ~12 hour figure belongs to regions.

A SEPARATE bundle from examples/perm-graph/bundle.json: same block, different page, and folding
these curves in would make the Methods index download 278 KB of per-prefix potentials and currents
to draw a chart.

Run:  pixi run python -m scripts.gen_frontier_bundle
"""
from __future__ import annotations

import json
from pathlib import Path

from reblock.budget import building_radii, displacement, street_first_ordered
from reblock.compare import load_permeability_config
from reblock.derive.access import STREET_TOL
from reblock.derive.adjacency import parcel_adjacency
from reblock.permeability import egress_power, permeability
from scripts._example_block import load_example_block

OUT = Path("examples/method-comparison/frontier.json")
DTS = Path("web/src/frontier.d.ts")
SIGFIGS = 6


def _r(x: float) -> float:
    """6 significant digits. Safe here because every value is a metric in [0, 1] or a road length in
    the hundreds -- unlike coordinates, which need absolute rounding (see gen_web_bundle._c)."""
    return float(f"%.{SIGFIGS}g" % x)


def main() -> None:
    block, roads_by_method = load_example_block()
    pcfg = load_permeability_config()
    params = pcfg.params

    # Both frozen once and threaded through every solve: functions of block geometry alone.
    adj = parcel_adjacency(list(block.parcels.geometry), STREET_TOL)
    p0, _ = egress_power(block, None, params, adj=adj)
    radii = building_radii(block.building_points)
    n_buildings = len(block.building_points)

    methods: dict[str, dict[str, list[float]]] = {}
    for name, roads in roads_by_method.items():
        ordered = street_first_ordered(block, roads, STREET_TOL)
        road_m, disp, perm = [], [], []
        for m in range(len(ordered) + 1):
            prefix = ordered.iloc[:m]
            road_m.append(_r(float(prefix.geometry.length.sum())))
            disp.append(_r(displacement(block.building_points, radii, prefix) / n_buildings
                           if n_buildings else 0.0))
            perm.append(_r(permeability(block, prefix, params, p0=p0, adj=adj)))
        methods[name] = {"road_m": road_m, "displacement": disp, "permeability": perm}

    bundle = {
        "block_id": block.block_id,
        # The widget boots with its target lines here, matching the dashed guides on the fallback
        # PNG -- whose caption the reader is looking at. Read from conf, never typed.
        "matched_displacement": pcfg.matched_displacement,
        "matched_permeability": pcfg.matched_permeability,
        "frontier_xmax": pcfg.frontier_xmax,
        "methods": methods,
    }
    OUT.write_text(json.dumps(bundle) + "\n", encoding="utf-8")
    DTS.write_text(DTS_TEMPLATE, encoding="utf-8")


DTS_TEMPLATE = '''// GENERATED by scripts/gen_frontier_bundle.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_frontier_bundle
export interface MethodCurve {
  road_m: number[];
  displacement: number[];
  permeability: number[];
}
export interface FrontierBundle {
  block_id: string;
  matched_displacement: number;
  matched_permeability: number;
  frontier_xmax: number;
  methods: Record<string, MethodCurve>;
}
'''


if __name__ == "__main__":
    main()
