"""Bake the browser bundle for the Permeability page's PermGraph widget.

Everything the widget draws is computed HERE, in Python, and read there: geometry, the
per-prefix fields, the colour ramp, and the width rules. The widget's only freedoms are which
prefix and which layer. That is deliberate -- the widget replaces a PNG whose caption quotes
numbers from `perm_graph.json`, so a second opinion about how to draw the same data would put two
pictures under one caption.

Committed, not built in CI: `scripts/gen_site_pages.py` is stdlib-only (CI builds the site with
only mkdocs-material installed) and baking needs geopandas and the solver.

Run:  pixi run python -m scripts.gen_web_bundle
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import cast

import numpy as np
from geopandas import GeoDataFrame
from matplotlib import colormaps

from reblock.budget import prefix_to_permeability, street_first_ordered
from reblock.compare import load_permeability_config
from reblock.contracts import Block
from reblock.derive.access import STREET_TOL
from reblock.perm_graph import GRAPH_LAYERS, permeability_graph
from reblock.permeability import EgressContext
from reblock.render import (
    _BOUNDARY_COLOR,
    _CONTEXT_OUTLINE,
    _EDGE_GREY,
    _EDGE_LW_MAX,
    _EDGE_LW_MIN,
    _NODE_RADIUS_FRAC,
    _PERM_CMAP,
    _ROAD_COLOR,
    _UPGRADED_LW,
)
from scripts._bundle_io import cm, line_coords, polygon_rings, sigfig
from scripts._example_block import PINNED_METHOD, load_example_block

log = logging.getLogger(__name__)

OUT = Path("examples/perm-graph")
DTS = Path("web/src/bundle.d.ts")


def load_block_and_roads() -> tuple[Block, GeoDataFrame]:
    """Kept as a thin alias so tests/test_web_bundle.py's parity test still imports one name."""
    block, roads = load_example_block(PINNED_METHOD)
    return block, roads[PINNED_METHOD]


def _ramp(name: str, n: int = 256) -> list[str]:
    """The colormap sampled to hex stops. `_PERM_CMAP` is the STRING "YlOrRd" -- a matplotlib
    colormap name -- and the browser has no matplotlib, so a hand-rolled JS approximation would put
    the same block in two palettes on one page (the drift the parent design warns about)."""
    cmap = colormaps[name]
    stops = []
    for t in np.linspace(0.0, 1.0, n):
        r, g, b = (int(round(c * 255)) for c in cmap(t)[:3])
        stops.append(f"#{r:02x}{g:02x}{b:02x}")
    return stops


DTS_TEMPLATE = '''// GENERATED by scripts/gen_web_bundle.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_web_bundle
// This file is what makes a renamed Python field a TypeScript error instead of a blank panel.
export interface Encoding {
  width_norm: { conductance: number; current: number };
  edge_lw_min: number;
  edge_lw_max: number;
  upgraded_lw: number;
  node_radius_frac: number;
  ramp: string[];
  road_color: string;
  boundary_color: string;
  parcel_color: string;
  edge_color: string;
}
export interface Bundle {
  block_id: string;
  method: string;
  /** UTM easting/northing subtracted from every coordinate below; all geometry is local metres. */
  origin: [number, number];
  parcels: [number, number][][];
  /** The block's rings, EXTERIOR FIRST -- relative to `origin`. Rings, not a ring: a block
   * boundary can have interior rings and `ZAF.9.3.1_1_5810`'s does, so an exterior-only field
   * would draw an outline with a hole missing from it. Each is stroked closed and none is
   * filled, so there is no even-odd rule to get right. Fallback-parity background layer; see
   * `_draw_boundary_and_streets` in render.py, which draws this under the graph on every PNG. */
  boundary: [number, number][][];
  /** Existing street network, relative to `origin`; one entry per disjoint line (a block's
   * streets are not always a single connected LineString). Fallback-parity, same as `boundary`. */
  streets: [number, number][][];
  nodes: { cx: number[]; cy: number[]; ground_g: number[] };
  edges: { rows: number[]; cols: number[]; footpath_g: number[] };
  roads: { coords: [number, number][]; width_m: number }[];
  encoding: Encoding;
}
'''


def main() -> None:
    logging.basicConfig(level=logging.INFO)
    OUT.mkdir(parents=True, exist_ok=True)
    pcfg = load_permeability_config()
    params = pcfg.params

    block, roads = load_block_and_roads()

    ordered = street_first_ordered(block, roads, STREET_TOL)
    ctx = EgressContext.of(block, params)
    prefix, reached = prefix_to_permeability(ctx, roads, pcfg.matched_permeability,
                                            tol=STREET_TOL)
    if not reached:
        raise SystemExit(f"{PINNED_METHOD} never reached P*={pcfg.matched_permeability}")
    # prefix_to_permeability returns `ordered.iloc[:lo]`, so its LENGTH is the index into the
    # canonical sequence -- this is the prefix graph_current_after.png shows, and the widget must
    # boot here or the caption below it describes a different picture.
    lens_b_index = len(prefix)

    # TWO prefixes, not all of them. This used to solve every prefix m in 0..len(ordered) and bake
    # a full potential field (one value per parcel) and current field (one per edge) for each, so
    # the reader could scrub road-by-road. That was 21 frames x 1,008 values on the 263-parcel
    # block this was written for; on `ZAF.9.3.1_1_5810` it became 320 x 26,062 -- an 83 MB bundle,
    # of which `prefix` was 98.1%, for a page asset. The build-order animation it fed is now the
    # committed `reblock_<method>.gif`, which `gen_example` already bakes for every method and
    # which already stops at the matched-permeability standard -- 850 KB against 80 MB, and no
    # solver in the browser to feed it.
    #
    # What still needs a solve is `width_norm`: the drawing scale DrawRoad reads out of this
    # bundle's `encoding`. m=0 and the Lens-B index are exactly the two `gen_perm_graph.py` pools
    # its PNG norm over, and this file's own note already recorded that pooling every prefix
    # reproduces that two-prefix number precisely (the per-prefix mesh p99 falls monotonically,
    # so the maximum lands at m=0). So this is the same number by a cheaper route, not a weaker one.
    figs = [permeability_graph(ctx, cast(GeoDataFrame, ordered.iloc[:m]))
            for m in (0, lens_b_index)]
    base = figs[0]

    # Mesh-only width norms (fix wave, C2): for each layer, the TRUE MAXIMUM over every prefix m of
    # that layer's p99, restricted to prefix m's OWN mesh (edges not yet upgraded at m -- the same
    # mesh mask `render_graph` excludes upgraded edges from before taking its own p99). Prefix m's
    # mesh shrinks monotonically as roads raise more edges, so this is a slider-independent scalar:
    # one fixed number per layer, computed once here, never recomputed per prefix in the browser.
    #
    # This reproduces gen_perm_graph.py's PNG norm exactly, because that norm is the SAME rule
    # pooled over only two prefixes (0 and the Lens-B index) rather than all of them -- a subset of
    # what is computed here, so this can only match or exceed it, never fall short. Measured on this
    # block: per-prefix mesh p99 for `current` falls monotonically across every prefix, 3.9367 at
    # m=0 down to 0.58 at the full network, so the maximum lands at m=0 and pooling every prefix
    # reproduces the PNG's 3.9367 precisely. It clips nothing, by construction: every prefix's own
    # mesh p99 is <= this maximum, so no mesh edge at any prefix can exceed `edge_lw_max`.
    width_norm = {
        layer: sigfig(max(float(np.percentile(np.abs(read(f)[~f.upgraded]), 99))
                          if (~f.upgraded).any() else 0.0
                          for f in figs))
        for layer, read in GRAPH_LAYERS.items()
    }

    # Everything geometric is emitted RELATIVE to this, in metres. The canvas works in local metres
    # and never learns the CRS; `width_m` is a length, so translation leaves it alone.
    ox, oy = float(base.cx.min()), float(base.cy.min())

    # EVERY ring, flattened: `Drawable.parcels` is one entry per RING, not per parcel -- `draw`
    # strokes each as a closed outline and never asks which parcel it belongs to, which is also
    # how DrawRoad consumes the authoring bundle's per-parcel ring lists. So a hole costs one more
    # entry and nothing else; there is no fill and therefore no even-odd question here.
    # `polygon_ring` used to be called instead, and RAISED on a parcel with holes -- which is how
    # `ZAF.9.3.1_1_5810` was found to have exactly 1 holed parcel of 6,619 when the Explore page
    # was repinned to it. Dropping the hole was never an option: it would have inflated that
    # parcel's area and changed the permeability the widget solves.
    parcel_coords = [ring for g in block.parcels.geometry
                     for ring in polygon_rings(g, ox, oy,
                                               what=f"block {block.block_id!r}'s parcel")]

    # Fallback parity: _draw_boundary_and_streets (render.py) draws the block outline and the
    # EXISTING street network under every graph PNG, including graph_current_after.png -- the
    # exact image this widget replaces. The widget draws neither unless the bundle carries the
    # geometry, so bake it here rather than let the interactive version silently omit context the
    # static fallback always shows.
    #
    # Rings, not a ring: `ZAF.9.3.1_1_5810`'s own boundary has an interior ring, so the exterior
    # alone would draw a block outline with a hole missing from it. `polygon_rings` still raises
    # on a MultiPolygon, which `load_block_and_roads` asserts cannot arise for this figure set.
    boundary_coords = polygon_rings(block.boundary, ox, oy,
                                    what=f"block {block.block_id!r}'s boundary")

    street_coords: list[list[list[float]]] = []
    for g in block.streets.geometry:
        street_coords.extend(line_coords(g, ox, oy))

    bundle = {
        "block_id": block.block_id,
        "method": PINNED_METHOD,
        "origin": [ox, oy],
        "parcels": parcel_coords,
        "boundary": boundary_coords,
        "streets": street_coords,
        "nodes": {"cx": [cm(v - ox) for v in base.cx], "cy": [cm(v - oy) for v in base.cy],
                  "ground_g": [sigfig(v) for v in base.ground_g]},
        "edges": {"rows": base.rows.tolist(), "cols": base.cols.tolist(),
                  "footpath_g": [sigfig(v) for v in base.footpath_g]},
        "roads": [{"coords": [[cm(x - ox), cm(y - oy)] for x, y in g.coords],
                   "width_m": float(w)}
                  for g, w in zip(ordered.geometry, ordered["width_m"], strict=True)],
        "encoding": {
            "width_norm": width_norm,
            "edge_lw_min": _EDGE_LW_MIN, "edge_lw_max": _EDGE_LW_MAX,
            "upgraded_lw": _UPGRADED_LW, "node_radius_frac": _NODE_RADIUS_FRAC,
            "ramp": _ramp(_PERM_CMAP),
            "road_color": _ROAD_COLOR, "boundary_color": _BOUNDARY_COLOR,
            "parcel_color": _CONTEXT_OUTLINE, "edge_color": _EDGE_GREY,
        },
    }
    (OUT / "bundle.json").write_text(json.dumps(bundle) + "\n", encoding="utf-8")
    log.info("wrote %s", OUT / "bundle.json")

    DTS.parent.mkdir(parents=True, exist_ok=True)
    DTS.write_text(DTS_TEMPLATE, encoding="utf-8")
    log.info("wrote %s", DTS)


if __name__ == "__main__":
    main()
