// GENERATED by scripts/gen_authoring_block.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_authoring_block
// This file is what makes a renamed Python field a TypeScript error instead of a blank panel.
/** One fixed road and CPython's own permeability for it. DEBT: baked so that Task 5's
 * `web/test/pyodide-parity.test.ts` will need no Python process at test time -- the same device
 * `field.json` and `hood.json` already use. That test does not exist yet. */
export interface AuthoringReference {
  name: string;
  road: [number, number][];
  permeability: number;
}
export interface AuthoringBlock {
  block_id: string;
  /** Projected, and asserted so by the baker: `Block.__post_init__` rejects a geographic CRS,
   * and a browser-side failure there would surface as a Pyodide traceback in a figcaption. */
  crs_epsg: number;
  /** FULL float64, NOT the cm-rounded form the render bundles ship. MEASURED: rounding this
   * bundle's geometry to centimetres and re-solving moves `crossing` by 1.6611e-03 and `spur` by
   * 1.9550e-03; design §1.4's 4.71e-05 is the same effect on the clearance method's road set, and
   * is the smaller figure. Either is more than a runtime-parity guard can absorb.
   * Exterior ring first, then interiors -- the same shape every `parcels` entry has. */
  boundary: [number, number][][];
  parcel_id: string[];
  parcels: [number, number][][][];
  streets: [number, number][][];
  /** One per parcel, but NOT in parcel order -- `parcel_radii` resolves the correspondence by
   * containment, and this bundle preserves whatever order the source had rather than inventing
   * one the Python does not rely on. */
  building_points: [number, number][];
  reference: AuthoringReference[];

  /** The road-INVARIANT half of the graph (design §1.6), baked once so the runtime returns two
   * arrays rather than a mesh. Parcel centroids and the footpath edge list do not move when a
   * road is drawn; only the conductances on those edges do. */
  nodes: { cx: number[]; cy: number[]; ground: boolean[] };
  edges: { rows: number[]; cols: number[]; footpath_g: number[] };
  /** `solve_egress(block, None)`'s own answer: the no-roads baseline permeability divides
   * against, and the potentials the "before" picture shows. Road-invariant, so computing it in
   * the browser on every edit would be waste. */
  baseline: { p0: number; potential: number[] };
}
