// GENERATED by scripts/gen_authoring_block.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_authoring_block
// This file is what makes a renamed Python field a TypeScript error instead of a blank panel.
/** One fixed road and CPython's own permeability for it. Baked so that
 * `web/test/pyodide-parity.test.ts` needs no Python process at test time -- the same device
 * `field.json` and `hood.json` already use. */
export interface AuthoringReference {
  name: string;
  road: [number, number][];
  permeability: number;
}
export interface AuthoringBlock {
  block_id: string;
  /** Projected, and asserted so by the baker: `Block.__post_init__` rejects a geographic CRS,
   * and a browser-side failure there would surface as a Pyodide traceback in a figcaption. */
  crs_epsg: number;
  /** FULL float64, NOT the cm-rounded form the render bundles ship. MEASURED: rounding this
   * bundle's geometry to centimetres and re-solving moves `crossing` by 5.3129e-05 and `spur` by
   * 4.6081e-05; design §1.4's 4.71e-05 is the same effect on the clearance method's road set. Any
   * of them is more than a runtime-parity guard can absorb.
   * Exterior ring first, then interiors -- the same shape every `parcels` entry has. */
  boundary: [number, number][][];
  parcel_id: string[];
  parcels: [number, number][][][];
  streets: [number, number][][];
  /** Each building's ANCHOR -- the point its parcel was tessellated on. One per parcel, but NOT in
   * parcel order -- `parcel_radii` resolves the correspondence by containment, and this bundle
   * preserves whatever order the source had rather than inventing one the Python does not rely
   * on. */
  building_points: [number, number][];
  /** Each building's radius AT THE BLOCK'S TIER, full float64, in `building_points` order. The
   * solve reads a building only as a radius at its anchor, so rebuilding the block as
   * `Discs(building_points, building_radii)` reproduces whatever tier baked it -- a footprint's
   * equivalent-area radius included -- without shipping a single polygon. */
  building_radii: number[];
  /** `PermeabilityParams`, field for field, baked from conf/permeability.yaml: `conf/` does not
   * travel with the wheel the browser installs, so the solve builds its params from these. */
  params: {
    g_walk: number;
    g_road_per_m: number;
    g_street: number;
    road_margin_m: number;
    min_road_width_m: number;
    radius_frac: number;
  };
  reference: AuthoringReference[];

  /** The road-INVARIANT half of the graph (design §1.6), baked once so the runtime returns two
   * arrays rather than a mesh. Parcel centroids and the footpath edge list do not move when a
   * road is drawn; only the conductances on those edges do. */
  nodes: { cx: number[]; cy: number[]; ground: boolean[] };
  edges: { rows: number[]; cols: number[]; footpath_g: number[] };
  /** `solve_egress(ctx, None)`'s own answer: the no-roads baseline permeability divides
   * against, and the potentials the "before" picture shows. Road-invariant, so computing it in
   * the browser on every edit would be waste. */
  baseline: { p0: number; potential: number[] };
}
