// GENERATED by scripts/gen_web_bundle.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_web_bundle
// This file is what makes a renamed Python field a TypeScript error instead of a blank panel.
export interface Encoding {
  width_norm: { conductance: number; current: number };
  edge_lw_min: number;
  edge_lw_max: number;
  upgraded_lw: number;
  node_radius_frac: number;
  ramp: string[];
  road_color: string;
  boundary_color: string;
  parcel_color: string;
  edge_color: string;
}
export interface Bundle {
  block_id: string;
  method: string;
  /** UTM easting/northing subtracted from every coordinate below; all geometry is local metres. */
  origin: [number, number];
  parcels: [number, number][][];
  /** The block's rings, EXTERIOR FIRST -- relative to `origin`. Rings, not a ring: a block
   * boundary can have interior rings and `ZAF.9.3.1_1_5810`'s does, so an exterior-only field
   * would draw an outline with a hole missing from it. Each is stroked closed and none is
   * filled, so there is no even-odd rule to get right. Fallback-parity background layer; see
   * `_draw_boundary_and_streets` in render.py, which draws this under the graph on every PNG. */
  boundary: [number, number][][];
  /** Existing street network, relative to `origin`; one entry per disjoint line (a block's
   * streets are not always a single connected LineString). Fallback-parity, same as `boundary`. */
  streets: [number, number][][];
  nodes: { cx: number[]; cy: number[]; ground_g: number[] };
  edges: { rows: number[]; cols: number[]; footpath_g: number[] };
  roads: { coords: [number, number][]; width_m: number }[];
  encoding: Encoding;
}
