// GENERATED by scripts/gen_displacement_field.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_displacement_field
// This file is what makes a renamed Python field a TypeScript error instead of a blank panel.
export interface Encoding {
  parcel_color: string;
  parcel_lw: number;
  boundary_color: string;
  boundary_lw: number;
  street_lw: number;
  road_color: string;
  road_alpha: number;
  disk_color: string;
  disk_outline_lw: number;
  handle_radius_px: number;
  pad: number;
}
export interface Width {
  /** The slider's floor IS PermeabilityParams.min_road_width_m: the pipeline raises below it. */
  floor_m: number;
  max_m: number;
  step_m: number;
  default_m: number;
}
export interface Road {
  coords: [number, number][];
  width_m: number;
}
/** A road configuration plus Python's own sum of c_i for it -- the parity fixtures. `sum_c` is
 * measured on THESE coordinates and on `buildings` as quantised below, not on the unrounded
 * geometry they came from, so the parity tolerance measures the formula and not the quantiser. */
export interface ReferenceCase {
  name: string;
  roads: Road[];
  sum_c: number;
  fraction: number;
}
export interface FieldBundle {
  block_id: string;
  n_buildings: number;
  /** UTM easting/northing subtracted from every coordinate below; all geometry is local metres. */
  origin: [number, number];
  /** Disk centres (relative to `origin`) and radii, in metres, in building order. */
  buildings: { x: number[]; y: number[]; r: number[] };
  parcels: [number, number][][];
  /** Block exterior ring, relative to `origin` -- the ring the fallback PNG draws. */
  boundary: [number, number][];
  /** Existing street network, relative to `origin`; one entry per disjoint line (a block's
   * streets are not always a single connected LineString). Fallback-parity, same as `boundary`. */
  streets: [number, number][][];
  /** Road 1 and road 2 (the default-road rule). Road 2 boots OFF; the toggle adds it. */
  roads: Road[];
  width: Width;
  encoding: Encoding;
  reference: ReferenceCase[];
}
