// GENERATED by scripts/gen_frontier_bundle.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_frontier_bundle
export interface MethodCurve {
  road_m: number[];
  displacement: number[];
  permeability: number[];
}
export interface FrontierBundle {
  block_id: string;
  matched_displacement: number;
  matched_permeability: number;
  frontier_xmax: number;
  methods: Record<string, MethodCurve>;
}
