// GENERATED by scripts/gen_region_grow.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_region_grow
// This file is what makes a renamed Python field a TypeScript error instead of a blank panel.
export interface HoodBlock {
  block_id: string;
  /** building_count. The growth budget is measured in these. */
  n: number;
  area_m2: number;
  perimeter_m: number;
  /** Exterior ring first, then interiors. 7 of the 213 blocks have one. Fill even-odd. */
  rings: [number, number][][];
  /** Indices into `blocks`, not block_ids -- the greedy runs over these directly. */
  adj: number[];
}
/** Production's own accretion, for one seed at one budget -- the parity fixtures. */
export interface GrowthCase {
  seed: string;
  max_buildings: number;
  /** block_ids in ACCRETION order, straight out of DenseClusterRegionBuilder. */
  order: string[];
  buildings: number;
}
export interface Budget { min: number; max: number; step: number; default: number }
export interface HoodEncoding {
  hood_color: string;
  hood_lw: number;
  region_color: string;
  region_lw: number;
  /** The region fill's opacity -- matches hood.png's own alpha, so JS-on and JS-off draw
   * the same fill. */
  region_alpha: number;
  seed_color: string;
  frontier_color: string;
  pad: number;
}
export interface HoodBundle {
  city: string;
  /** The pinned seed -- the same block PermGraph, Frontier and DisplacementField use. */
  seed: string;
  /** UTM easting/northing subtracted from every coordinate; all geometry is local metres. */
  origin: [number, number];
  crs_epsg: number;
  blocks: HoodBlock[];
  budget: Budget;
  encoding: HoodEncoding;
  reference: GrowthCase[];
}
