// GENERATED by scripts/gen_screen_map.py -- do not edit.
// Regenerate: pixi run python -m scripts.gen_screen_map
export interface CityFloor {
  /** The metric this floor belongs to, as `reblock.metric` names it. */
  metric: string;
  value: number;
  n: number;
  /** Read from examples/screen-bakeoff/screen_comparison.csv, which computes them independently
   * of this bundle -- so the widget's own prefix arithmetic has something to be checked against. */
  precision: number | null;
  recall: number | null;
}
export interface CityEncoding {
  base_color: string;
  selected_color: string;
  informal_color: string;
  block_lw: number;
  pad: number;
}
export interface CityBundle {
  city: string;
  crs_epsg: number;
  origin: [number, number];
  n_blocks: number;
  /** Column arrays, not an array of objects: 16,451 blocks with repeated keys would add megabytes
   * of field names. Same shape as field.json's `buildings: {x, y, r}`. */
  block_id: string[];
  n: number[];
  area_m2: number[];
  perimeter_m: number[];
  /** Per block, exterior ring first then interiors. Fill even-odd. */
  rings: [number, number][][][];
  /** 0/1 ground truth. ABSENT for Nairobi -- see the README. Not a null column: a null column is
   * a field that looks answerable and is not. */
  informal?: number[];
  floors: CityFloor[];
  encoding: CityEncoding;
}
